"""baseline browser first schema

Revision ID: 5cda50f97ed9
Revises:
Create Date: 2026-08-13 19:20:08.227929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cda50f97ed9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('email_verificado_at', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categorias_partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('subcategoria', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_partidas_organizacion_id'), 'categorias_partidas', ['organizacion_id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rif', sa.String(length=50), nullable=True),
    sa.Column('pais', sa.String(length=80), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('es_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_organizacion_id'), 'clientes', ['organizacion_id'], unique=False)
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_nombre', sa.String(length=200), nullable=True),
    sa.Column('empresa_legal', sa.String(length=250), nullable=True),
    sa.Column('empresa_rif', sa.String(length=50), nullable=True),
    sa.Column('empresa_pais', sa.String(length=80), nullable=True),
    sa.Column('empresa_ciudad', sa.String(length=120), nullable=True),
    sa.Column('empresa_direccion', sa.Text(), nullable=True),
    sa.Column('empresa_telefono', sa.String(length=50), nullable=True),
    sa.Column('empresa_email', sa.String(length=200), nullable=True),
    sa.Column('empresa_web', sa.String(length=200), nullable=True),
    sa.Column('logo', sa.String(length=300), nullable=True),
    sa.Column('onboarding_completado', sa.Boolean(), nullable=True),
    sa.Column('onboarding_modo', sa.String(length=20), nullable=True),
    sa.Column('onboarding_iniciado_at', sa.DateTime(), nullable=True),
    sa.Column('onboarding_completado_at', sa.DateTime(), nullable=True),
    sa.Column('onboarding_catalogo_revisado', sa.Boolean(), nullable=True),
    sa.Column('onboarding_pdf_descargado', sa.Boolean(), nullable=True),
    sa.Column('primer_pdf_at', sa.DateTime(), nullable=True),
    sa.Column('iva_default', sa.Float(), nullable=True),
    sa.Column('moneda_default', sa.String(length=10), nullable=True),
    sa.Column('validez_default', sa.Integer(), nullable=True),
    sa.Column('notas_default', sa.Text(), nullable=True),
    sa.Column('condiciones_default', sa.Text(), nullable=True),
    sa.Column('pdf_color', sa.String(length=10), nullable=True),
    sa.Column('logo_ancho_pdf', sa.Float(), nullable=True),
    sa.Column('con_portada_default', sa.Boolean(), nullable=True),
    sa.Column('mostrar_firmas_default', sa.Boolean(), nullable=True),
    sa.Column('mostrar_resumen_capitulos_default', sa.Boolean(), nullable=True),
    sa.Column('mostrar_garantias_default', sa.Boolean(), nullable=True),
    sa.Column('activar_funciones_avanzadas', sa.Boolean(), nullable=True),
    sa.Column('mostrar_costes_internos', sa.Boolean(), nullable=True),
    sa.Column('mostrar_alternativas', sa.Boolean(), nullable=True),
    sa.Column('mostrar_cargos_adicionales', sa.Boolean(), nullable=True),
    sa.Column('activar_funciones_venezuela', sa.Boolean(), nullable=True),
    sa.Column('mostrar_numero_control', sa.Boolean(), nullable=True),
    sa.Column('mostrar_tasa_cambio', sa.Boolean(), nullable=True),
    sa.Column('mostrar_total_bs', sa.Boolean(), nullable=True),
    sa.Column('mostrar_retenciones', sa.Boolean(), nullable=True),
    sa.Column('mostrar_clausula_cambiaria', sa.Boolean(), nullable=True),
    sa.Column('datos_bancarios', sa.Text(), nullable=True),
    sa.Column('horas_jornada', sa.Float(), nullable=True),
    sa.Column('tarifa_hora_media', sa.Float(), nullable=True),
    sa.Column('estimar_tiempo_por_coste', sa.Boolean(), nullable=True),
    sa.Column('semilla_catalogo_aplicada', sa.Boolean(), nullable=True),
    sa.Column('semilla_productos_aplicada', sa.Boolean(), nullable=True),
    sa.Column('semilla_recetas_aplicada', sa.Boolean(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_organizacion_id'), 'configuracion', ['organizacion_id'], unique=False)
    op.create_table('membresias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("rol IN ('propietario', 'administrador', 'miembro', 'lectura')", name='ck_membresia_rol_valido'),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'organizacion_id', name='uq_membresia_usuario_organizacion')
    )
    op.create_index(op.f('ix_membresias_organizacion_id'), 'membresias', ['organizacion_id'], unique=False)
    op.create_index(op.f('ix_membresias_usuario_id'), 'membresias', ['usuario_id'], unique=False)
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('usos', sa.Integer(), nullable=True),
    sa.Column('ultimo_uso', sa.DateTime(), nullable=True),
    sa.Column('codigo_interno', sa.String(length=80), nullable=True),
    sa.Column('subcategoria', sa.String(length=80), nullable=True),
    sa.Column('coste_materiales', sa.Float(), nullable=True),
    sa.Column('coste_mano_obra', sa.Float(), nullable=True),
    sa.Column('coste_complementarios', sa.Float(), nullable=True),
    sa.Column('coste_otros', sa.Float(), nullable=True),
    sa.Column('tiempo_estimado_horas', sa.Float(), nullable=True),
    sa.Column('tiempo_oficial_horas', sa.Float(), nullable=True),
    sa.Column('tiempo_ayudante_horas', sa.Float(), nullable=True),
    sa.Column('tiempo_equipo_horas', sa.Float(), nullable=True),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('rendimiento', sa.String(length=120), nullable=True),
    sa.Column('desperdicio_recomendado_pct', sa.Float(), nullable=True),
    sa.Column('imagen', sa.String(length=300), nullable=True),
    sa.Column('notas_tecnicas', sa.Text(), nullable=True),
    sa.Column('codigo_externo', sa.String(length=100), nullable=True),
    sa.Column('descomposicion_json', sa.Text(), nullable=True),
    sa.Column('fecha_actualizacion_precio', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'nombre', name='uq_partida_organizacion_nombre')
    )
    op.create_index(op.f('ix_partidas_organizacion_id'), 'partidas', ['organizacion_id'], unique=False)
    op.create_table('plantillas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('datos', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantillas_organizacion_id'), 'plantillas', ['organizacion_id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('imagen', sa.String(length=300), nullable=True),
    sa.Column('precio_compra', sa.Float(), nullable=True),
    sa.Column('fecha_actualizacion_precio', sa.DateTime(), nullable=True),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('acabado', sa.String(length=120), nullable=True),
    sa.Column('formato', sa.String(length=120), nullable=True),
    sa.Column('tiempo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('variantes', sa.Text(), nullable=True),
    sa.Column('ficha_tecnica', sa.String(length=300), nullable=True),
    sa.Column('imagenes', sa.Text(), nullable=True),
    sa.Column('usos', sa.Integer(), nullable=True),
    sa.Column('ultimo_uso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'nombre', name='uq_producto_organizacion_nombre')
    )
    op.create_index(op.f('ix_productos_organizacion_id'), 'productos', ['organizacion_id'], unique=False)
    op.create_table('recetas_estancia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('unidad_base', sa.String(length=20), nullable=True),
    sa.Column('cantidad_base_default', sa.Float(), nullable=True),
    sa.Column('datos', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_estancia_organizacion_id'), 'recetas_estancia', ['organizacion_id'], unique=False)
    op.create_table('recursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('grupo', sa.String(length=250), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('usos', sa.Integer(), nullable=True),
    sa.Column('ultimo_uso', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion_precio', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recursos_organizacion_id'), 'recursos', ['organizacion_id'], unique=False)
    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=True),
    sa.Column('direccion_obra', sa.String(length=300), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('validez_dias', sa.Integer(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('tipo_cambio', sa.Float(), nullable=True),
    sa.Column('impuesto_pct', sa.Float(), nullable=True),
    sa.Column('descuento_pct', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('es_demo', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('con_portada', sa.Boolean(), nullable=True),
    sa.Column('foto_proyecto', sa.String(length=300), nullable=True),
    sa.Column('mostrar_firmas', sa.Boolean(), nullable=True),
    sa.Column('mostrar_resumen_capitulos', sa.Boolean(), nullable=True),
    sa.Column('mostrar_garantias', sa.Boolean(), nullable=True),
    sa.Column('firma_cliente', sa.String(length=300), nullable=True),
    sa.Column('usar_funciones_avanzadas', sa.Boolean(), nullable=True),
    sa.Column('gastos_indirectos_pct', sa.Float(), nullable=True),
    sa.Column('imprevistos_pct', sa.Float(), nullable=True),
    sa.Column('transporte_monto', sa.Float(), nullable=True),
    sa.Column('otros_cargos_monto', sa.Float(), nullable=True),
    sa.Column('estilo_pdf', sa.String(length=30), nullable=True),
    sa.Column('mostrar_ahorro', sa.Boolean(), nullable=True),
    sa.Column('incluir_anexos', sa.Boolean(), nullable=True),
    sa.Column('numero_control', sa.String(length=80), nullable=True),
    sa.Column('fecha_tipo_cambio', sa.Date(), nullable=True),
    sa.Column('retencion_pct', sa.Float(), nullable=True),
    sa.Column('operacion_exenta', sa.Boolean(), nullable=True),
    sa.Column('clausula_cambiaria', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'numero', name='uq_presupuesto_organizacion_numero')
    )
    op.create_index(op.f('ix_presupuestos_organizacion_id'), 'presupuestos', ['organizacion_id'], unique=False)
    op.create_table('borradores_presupuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('datos', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('presupuesto_id')
    )
    op.create_index(op.f('ix_borradores_presupuesto_organizacion_id'), 'borradores_presupuesto', ['organizacion_id'], unique=False)
    op.create_table('capitulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capitulos_organizacion_id'), 'capitulos', ['organizacion_id'], unique=False)
    op.create_table('notas_seguimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_seguimiento_organizacion_id'), 'notas_seguimiento', ['organizacion_id'], unique=False)
    op.create_table('presupuesto_anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('archivo', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuesto_anexos_organizacion_id'), 'presupuesto_anexos', ['organizacion_id'], unique=False)
    op.create_table('presupuesto_versiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('numero_version', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('datos_snapshot', sa.Text(), nullable=False),
    sa.Column('pdf_snapshot', sa.String(length=300), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuesto_versiones_organizacion_id'), 'presupuesto_versiones', ['organizacion_id'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=True),
    sa.Column('direccion_obra', sa.String(length=300), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('impuesto_pct', sa.Float(), nullable=True),
    sa.Column('descuento_pct', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('presupuesto_id', sa.Integer(), nullable=True),
    sa.Column('presupuesto_version_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.ForeignKeyConstraint(['presupuesto_version_id'], ['presupuesto_versiones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'numero', name='uq_factura_organizacion_numero')
    )
    op.create_index(op.f('ix_facturas_organizacion_id'), 'facturas', ['organizacion_id'], unique=False)
    op.create_table('presupuesto_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('partida_catalogo_id', sa.Integer(), nullable=True),
    sa.Column('producto_nombre', sa.String(length=250), nullable=True),
    sa.Column('producto_precio', sa.Float(), nullable=True),
    sa.Column('producto_coste', sa.Float(), nullable=True),
    sa.Column('producto_unidad', sa.String(length=20), nullable=True),
    sa.Column('producto_imagen', sa.String(length=300), nullable=True),
    sa.Column('tipo_partida', sa.String(length=20), nullable=True),
    sa.Column('seleccionada', sa.Boolean(), nullable=True),
    sa.Column('coste_materiales', sa.Float(), nullable=True),
    sa.Column('coste_mano_obra', sa.Float(), nullable=True),
    sa.Column('coste_complementarios', sa.Float(), nullable=True),
    sa.Column('coste_otros', sa.Float(), nullable=True),
    sa.Column('desperdicio_pct', sa.Float(), nullable=True),
    sa.Column('margen_pct', sa.Float(), nullable=True),
    sa.Column('grupo_alternativa', sa.String(length=120), nullable=True),
    sa.Column('mostrar_en_pdf', sa.Boolean(), nullable=True),
    sa.Column('codigo_externo', sa.String(length=100), nullable=True),
    sa.Column('tiempo_manual_horas', sa.Float(), nullable=True),
    sa.Column('tiempo_manual_oficial_horas', sa.Float(), nullable=True),
    sa.Column('tiempo_manual_ayudante_horas', sa.Float(), nullable=True),
    sa.Column('tiempo_manual_equipo_horas', sa.Float(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulos.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partida_catalogo_id'], ['partidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuesto_items_organizacion_id'), 'presupuesto_items', ['organizacion_id'], unique=False)
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_version_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_estimada_fin', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.ForeignKeyConstraint(['presupuesto_version_id'], ['presupuesto_versiones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('presupuesto_id')
    )
    op.create_index(op.f('ix_proyectos_organizacion_id'), 'proyectos', ['organizacion_id'], unique=False)
    op.create_table('cambios_alcance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('diferencia_total', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cambios_alcance_organizacion_id'), 'cambios_alcance', ['organizacion_id'], unique=False)
    op.create_table('descomposiciones_partida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('nombre_hoja', sa.String(length=200), nullable=True),
    sa.Column('archivo_origen', sa.String(length=300), nullable=True),
    sa.Column('nombre_archivo_origen', sa.String(length=300), nullable=True),
    sa.Column('rango_original', sa.String(length=100), nullable=True),
    sa.Column('columnas_json', sa.Text(), nullable=True),
    sa.Column('rangos_combinados_json', sa.Text(), nullable=True),
    sa.Column('filas_originales_json', sa.Text(), nullable=True),
    sa.Column('coste_directo_unitario', sa.Float(), nullable=True),
    sa.Column('origen', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partida_id'], ['presupuesto_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partida_id')
    )
    op.create_index(op.f('ix_descomposiciones_partida_organizacion_id'), 'descomposiciones_partida', ['organizacion_id'], unique=False)
    op.create_table('factura_capitulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factura_capitulos_organizacion_id'), 'factura_capitulos', ['organizacion_id'], unique=False)
    op.create_table('mediciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=250), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partida_id'], ['presupuesto_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediciones_organizacion_id'), 'mediciones', ['organizacion_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('presupuesto_id', sa.Integer(), nullable=True),
    sa.Column('factura_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('metodo', sa.String(length=80), nullable=True),
    sa.Column('referencia', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('comprobante', sa.String(length=300), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_organizacion_id'), 'pagos', ['organizacion_id'], unique=False)
    op.create_table('presupuesto_item_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('coste', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('acabado', sa.String(length=120), nullable=True),
    sa.Column('imagen', sa.String(length=300), nullable=True),
    sa.Column('seleccionado', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partida_id'], ['presupuesto_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuesto_item_productos_organizacion_id'), 'presupuesto_item_productos', ['organizacion_id'], unique=False)
    op.create_table('cambio_alcance_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cambio_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cambio_id'], ['cambios_alcance.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cambio_alcance_items_organizacion_id'), 'cambio_alcance_items', ['organizacion_id'], unique=False)
    op.create_table('descomposicion_filas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descomposicion_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('numero_fila_excel', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('grupo', sa.String(length=250), nullable=True),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('codigo', sa.String(length=120), nullable=True),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('rendimiento', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=True),
    sa.Column('celdas_json', sa.Text(), nullable=True),
    sa.Column('formulas_json', sa.Text(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['descomposicion_id'], ['descomposiciones_partida.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_descomposicion_filas_organizacion_id'), 'descomposicion_filas', ['organizacion_id'], unique=False)
    op.create_table('factura_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capitulo_id'], ['factura_capitulos.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factura_items_organizacion_id'), 'factura_items', ['organizacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factura_items_organizacion_id'), table_name='factura_items')
    op.drop_table('factura_items')
    op.drop_index(op.f('ix_descomposicion_filas_organizacion_id'), table_name='descomposicion_filas')
    op.drop_table('descomposicion_filas')
    op.drop_index(op.f('ix_cambio_alcance_items_organizacion_id'), table_name='cambio_alcance_items')
    op.drop_table('cambio_alcance_items')
    op.drop_index(op.f('ix_presupuesto_item_productos_organizacion_id'), table_name='presupuesto_item_productos')
    op.drop_table('presupuesto_item_productos')
    op.drop_index(op.f('ix_pagos_organizacion_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_mediciones_organizacion_id'), table_name='mediciones')
    op.drop_table('mediciones')
    op.drop_index(op.f('ix_factura_capitulos_organizacion_id'), table_name='factura_capitulos')
    op.drop_table('factura_capitulos')
    op.drop_index(op.f('ix_descomposiciones_partida_organizacion_id'), table_name='descomposiciones_partida')
    op.drop_table('descomposiciones_partida')
    op.drop_index(op.f('ix_cambios_alcance_organizacion_id'), table_name='cambios_alcance')
    op.drop_table('cambios_alcance')
    op.drop_index(op.f('ix_proyectos_organizacion_id'), table_name='proyectos')
    op.drop_table('proyectos')
    op.drop_index(op.f('ix_presupuesto_items_organizacion_id'), table_name='presupuesto_items')
    op.drop_table('presupuesto_items')
    op.drop_index(op.f('ix_facturas_organizacion_id'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_presupuesto_versiones_organizacion_id'), table_name='presupuesto_versiones')
    op.drop_table('presupuesto_versiones')
    op.drop_index(op.f('ix_presupuesto_anexos_organizacion_id'), table_name='presupuesto_anexos')
    op.drop_table('presupuesto_anexos')
    op.drop_index(op.f('ix_notas_seguimiento_organizacion_id'), table_name='notas_seguimiento')
    op.drop_table('notas_seguimiento')
    op.drop_index(op.f('ix_capitulos_organizacion_id'), table_name='capitulos')
    op.drop_table('capitulos')
    op.drop_index(op.f('ix_borradores_presupuesto_organizacion_id'), table_name='borradores_presupuesto')
    op.drop_table('borradores_presupuesto')
    op.drop_index(op.f('ix_presupuestos_organizacion_id'), table_name='presupuestos')
    op.drop_table('presupuestos')
    op.drop_index(op.f('ix_recursos_organizacion_id'), table_name='recursos')
    op.drop_table('recursos')
    op.drop_index(op.f('ix_recetas_estancia_organizacion_id'), table_name='recetas_estancia')
    op.drop_table('recetas_estancia')
    op.drop_index(op.f('ix_productos_organizacion_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_plantillas_organizacion_id'), table_name='plantillas')
    op.drop_table('plantillas')
    op.drop_index(op.f('ix_partidas_organizacion_id'), table_name='partidas')
    op.drop_table('partidas')
    op.drop_index(op.f('ix_membresias_usuario_id'), table_name='membresias')
    op.drop_index(op.f('ix_membresias_organizacion_id'), table_name='membresias')
    op.drop_table('membresias')
    op.drop_index(op.f('ix_configuracion_organizacion_id'), table_name='configuracion')
    op.drop_table('configuracion')
    op.drop_index(op.f('ix_clientes_organizacion_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_categorias_partidas_organizacion_id'), table_name='categorias_partidas')
    op.drop_table('categorias_partidas')
    op.drop_table('usuarios')
    op.drop_table('organizaciones')
    # ### end Alembic commands ###
