#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Genera las partidas nuevas de los capítulos 15 (Gestión de residuos),
16 (Control de calidad y ensayos), 17 (Seguridad y salud) y 18 (Rehabilitación
energética) hasta el objetivo mínimo de la matriz de cobertura.

Solo usa recursos existentes en datos/recursos.json. Las partidas nuevas no
llevan codigo_legacy. El equipo de elección del cliente va en producto_cliente.
Uso:
    python3 tools/generar_capitulos_15_16_17_18.py
"""
from __future__ import annotations

import json
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
DESCOMP = BASE / "basedatos_partidas" / "datos" / "descompuestos"
CLASIF = BASE / "basedatos_partidas" / "datos" / "clasificacion.json"
RECURSOS = BASE / "basedatos_partidas" / "datos" / "recursos.json"

# --- recursos abreviados ---------------------------------------------------
O1_ALB = "MO-OF1-ALB"
O1_ELE = "MO-OF1-ELE"
O1_PLO = "MO-OF1-PLO"
O1_AC = "MO-OF1-AC"
O1_SOLD = "MO-OF1-SOLD"
O1_MON = "MO-OF1-MON"
O1_VIDR = "MO-OF1-VIDR"
O1_CARPM = "MO-OF1-CARPM"
O1_JARD = "MO-OF1-JARD"
O1_PIN = "MO-OF1-PIN"
AYU = "MO-AYU"


def r(ref: str, rendimiento: float) -> dict:
    return {"ref": ref, "rendimiento": rendimiento}


# ---------------------------------------------------------------------------
# 15. GESTIÓN DE RESIDUOS Y LIMPIEZA  (necesita 42 para llegar a 50)
# ---------------------------------------------------------------------------
CAP15 = {
    "01": [
        ("Sacos de rafia para clasificación de residuos.", "ud",
         "Suministro de sacos de rafia de alta resistencia para la clasificación y retirada manual de residuos de obra, apilados y etiquetados por tipo de material.",
         [r("MT-SAC-ESC", 1.0), r(AYU, 0.03)]),
        ("Zona de acopio de chatarra metálica.", "m²",
         "Habilitación de zona de acopio de chatarra metálica, delimitada y señalizada, para su venta o entrega a gestor autorizado.",
         [r("MT-MALLA-OBRA", 0.5), r("MT-SENAL-OBRA", 0.2), r("MT-PROT-OBRA", 1.0), r(AYU, 0.15)]),
        ("Zona de acopio de cartón y embalajes.", "m²",
         "Habilitación de zona de acopio de cartón y embalajes para su reciclaje, con protección del piso y señalización.",
         [r("MT-MALLA-OBRA", 0.5), r("MT-SENAL-OBRA", 0.2), r("MT-PROT-OBRA", 1.0), r(AYU, 0.15)]),
        ("Zona de acopio de madera y pallets.", "m²",
         "Habilitación de zona de acopio de madera y pallets para su reutilización o reciclaje, delimitada y señalizada.",
         [r("MT-MALLA-OBRA", 0.5), r("MT-SENAL-OBRA", 0.2), r("MT-PROT-OBRA", 1.0), r(AYU, 0.15)]),
        ("Separación selectiva de residuos en origen.", "m³",
         "Clasificación en origen de los residuos de demolición y desmontaje, separando los recuperables de los de vertedero, para abaratar el bote.",
         [r("MT-SAC-ESC", 0.5), r(AYU, 0.35)]),
        ("Identificación y etiquetado de contenedores de residuos.", "ud",
         "Colocación de identificación y etiquetado sobre los contenedores o zonas de acopio, indicando el tipo de residuo admitido.",
         [r("MT-SENAL-OBRA", 0.3), r(AYU, 0.1)]),
    ],
    "02": [
        ("Bajada de escombro por escombrera o ducto.", "m³",
         "Bajada de escombro desde plantas altas mediante escombrera o ducto vertical, con tolva de recepción y riego para control de polvo.",
         [r("MT-SAC-ESC", 0.4), r("MT-AGUA-OBRA", 0.01), r(AYU, 0.5)]),
        ("Bajada de escombro por medios manuales.", "m³",
         "Bajada de escombro desde plantas altas por medios manuales con sacos, hasta la zona de acopio en planta baja.",
         [r("MT-SAC-ESC", 0.6), r(AYU, 0.8)]),
        ("Bajada de escombro por montacargas.", "m³",
         "Bajada de escombro desde plantas altas mediante montacargas de obra, con carga y descarga manual.",
         [r("MT-SAC-ESC", 0.4), r("MQ-MONTAC", 0.1), r(AYU, 0.6)]),
        ("Carga manual de escombro sobre contenedor.", "m³",
         "Carga manual de escombro sobre contenedor o vehículo, con uso de pala y sacos, para su retirada.",
         [r("MT-SAC-ESC", 0.3), r(AYU, 0.4)]),
        ("Carga mecánica de escombro sobre vehículo.", "m³",
         "Carga mecánica de escombro sobre vehículo o volqueta con equipo adecuado, para su retirada a vertedero.",
         [r("MQ-RETRO", 0.05), r(AYU, 0.15)]),
        ("Movimiento interno de escombro a zona de acopio.", "m³",
         "Movimiento interno de escombro desde el punto de generación hasta la zona de acopio, con medios manuales o carretilla.",
         [r("MT-SAC-ESC", 0.3), r(AYU, 0.45)]),
    ],
    "03": [
        ("Contenedor de escombro de 3 m³, por mes.", "ud",
         "Alquiler mensual de contenedor de escombro de 3 m³, con su colocación y retirada por el gestor.",
         [r("MT-CONTENEDOR", 1.0), r(AYU, 0.2)]),
        ("Contenedor de chatarra metálica.", "ud",
         "Alquiler de contenedor destinado a chatarra metálica, con su colocación y retirada para entrega a gestor.",
         [r("MT-CONTENEDOR", 1.0), r(AYU, 0.2)]),
        ("Contenedor de residuos de madera.", "ud",
         "Alquiler de contenedor destinado a residuos de madera, con su colocación y retirada para reciclaje.",
         [r("MT-CONTENEDOR", 1.0), r(AYU, 0.2)]),
        ("Saco big-bag de escombro.", "ud",
         "Suministro y colocación de saco big-bag para acopio de escombro, con sus asas de izado para retirada con grúa.",
         [r("MT-SAC-ESC", 4.0), r(AYU, 0.15)]),
        ("Contenedor de residuos mezclados.", "ud",
         "Alquiler de contenedor de residuos mezclados no recuperables, con su colocación y retirada a vertedero.",
         [r("MT-CONTENEDOR", 1.0), r(AYU, 0.2)]),
        ("Acopio de escombro en sacos apilados.", "m³",
         "Acopio de escombro en sacos de rafia apilados en zona delimitada, a la espera de su retirada.",
         [r("MT-SAC-ESC", 1.0), r("MT-MALLA-OBRA", 0.3), r(AYU, 0.25)]),
    ],
    "04": [
        ("Transporte de escombro a vertedero autorizado.", "m³",
         "Transporte de escombro a vertedero o botadero autorizado, con vehículo y canon de vertido incluidos.",
         [r("MT-CANON", 1.0), r("MQ-VOLQ", 0.06), r(AYU, 0.1)]),
        ("Canon de vertido de escombro mezclado.", "m³",
         "Canon de vertido en vertedero autorizado de escombro mezclado no recuperable.",
         [r("MT-CANON", 1.0), r(AYU, 0.05)]),
        ("Retirada de chatarra metálica a gestor.", "kg",
         "Retirada y entrega de chatarra metálica a gestor autorizado, con carga y transporte.",
         [r("MQ-VOLQ", 0.01), r(AYU, 0.05)]),
        ("Retirada de cartón y embalajes a reciclaje.", "m³",
         "Retirada y entrega de cartón y embalajes a planta de reciclaje, con carga y transporte.",
         [r("MQ-VOLQ", 0.05), r(AYU, 0.1)]),
        ("Retirada de madera y pallets a reciclaje.", "m³",
         "Retirada y entrega de madera y pallets a planta de reciclaje o reutilización, con carga y transporte.",
         [r("MQ-VOLQ", 0.05), r(AYU, 0.1)]),
        ("Disposición de tierra de excavación.", "m³",
         "Disposición de tierra y material de excavación en botadero autorizado, con canon de vertido.",
         [r("MT-CANON-TIERRA", 1.0), r("MQ-VOLQ", 0.05), r(AYU, 0.1)]),
    ],
    "05": [
        ("Retiro de residuos de pinturas y disolventes.", "ud",
         "Recogida y entrega a gestor de residuos de pinturas, disolventes y envases contaminados, con su correcta identificación.",
         [r("MT-SAC-ESC", 2.0), r(AYU, 0.4)]),
        ("Retiro de residuos peligrosos menores.", "ud",
         "Recogida y entrega a gestor autorizado de residuos peligrosos menores (aerosoles, adhesivos, siliconas).",
         [r("MT-SAC-ESC", 2.0), r(AYU, 0.4)]),
        ("Retiro de tubos fluorescentes y lámparas.", "ud",
         "Recogida y entrega a gestor de tubos fluorescentes y lámparas de descarga, residuo con contenido de mercurio.",
         [r("MT-SAC-ESC", 1.0), r(AYU, 0.3)]),
        ("Retiro de baterías y pilas de obra.", "ud",
         "Recogida y entrega a gestor de baterías y pilas generadas en obra, residuo peligroso.",
         [r("MT-SAC-ESC", 1.0), r(AYU, 0.2)]),
        ("Gestión de aceites y lubricantes usados.", "ud",
         "Recogida y entrega a gestor de aceites y lubricantes usados de la maquinaria, en recipiente estanco.",
         [r("MT-SAC-ESC", 1.5), r(AYU, 0.35)]),
        ("Neutralización y limpieza de derrame menor.", "m²",
         "Neutralización y limpieza de derrame menor de sustancia química, con material absorbente y disposición del residuo.",
         [r("MT-CONS-LIMP", 0.5), r("MT-SAC-ESC", 0.5), r(AYU, 0.4)]),
    ],
    "06": [
        ("Limpieza diaria de zonas de trabajo.", "m²",
         "Limpieza diaria de las zonas de trabajo durante la ejecución, con retirada de restos y barrido, para mantener el orden y la seguridad.",
         [r("MT-CONS-LIMP", 0.05), r(AYU, 0.08)]),
        ("Limpieza semanal de la obra.", "m²",
         "Limpieza semanal general de la obra, con barrido, retirada de escombros menores y organización de materiales.",
         [r("MT-CONS-LIMP", 0.06), r("MT-SAC-ESC", 0.2), r(AYU, 0.1)]),
        ("Limpieza de zonas de paso y accesos.", "m²",
         "Limpieza de zonas de paso y accesos de la obra, para mantener la circulación despejada y segura.",
         [r("MT-CONS-LIMP", 0.04), r(AYU, 0.06)]),
        ("Limpieza de restos de mortero y adhesivos.", "m²",
         "Limpieza de restos de mortero y adhesivos de las superficies durante la obra, con rascado y retirada.",
         [r("MT-CONS-LIMP", 0.1), r(AYU, 0.15)]),
        ("Limpieza de escombro disperso en pisos.", "m²",
         "Limpieza del escombro disperso en pisos tras los trabajos de demolición y albañilería, con barrido y retirada.",
         [r("MT-SAC-ESC", 0.2), r(AYU, 0.12)]),
        ("Retirada de embalajes de la zona de trabajo.", "m²",
         "Retirada de embalajes y material de desecho de la zona de trabajo, con clasificación para reciclaje.",
         [r("MT-SAC-ESC", 0.25), r(AYU, 0.1)]),
    ],
    "07": [
        ("Limpieza final de obra para entrega.", "m²",
         "Limpieza final de obra previa a la entrega, con barrido, retirada de restos y limpieza de todas las superficies.",
         [r("MT-CONS-LIMP", 0.1), r(AYU, 0.12)]),
        ("Limpieza de vidrios y carpintería.", "m²",
         "Limpieza de vidrios, carpintería y herrajes al final de la obra, con productos adecuados y sin dejar residuos.",
         [r("MT-CONS-LIMP", 0.15), r(AYU, 0.2)]),
        ("Limpieza de aparatos sanitarios y grifería.", "ud",
         "Limpieza de aparatos sanitarios y grifería al final de la obra, con desincrustante y pulido.",
         [r("MT-CONS-LIMP", 0.2), r(AYU, 0.15)]),
        ("Limpieza de pisos con pulidora.", "m²",
         "Limpieza de pisos al final de la obra con máquina pulidora, para dejar el acabado listo para la entrega.",
         [r("MT-CONS-LIMP", 0.05), r("MQ-PULIDORA", 0.03), r(AYU, 0.08)]),
        ("Desinfección de zonas húmedas.", "m²",
         "Desinfección de zonas húmedas (baños, cocina) al final de la obra, con productos desinfectantes.",
         [r("MT-CONS-LIMP", 0.15), r(AYU, 0.1)]),
        ("Retirada final de protecciones y limpieza general.", "glb",
         "Retirada final de las protecciones de obra y limpieza general, dejando el inmueble en condiciones de entrega.",
         [r("MT-CONS-LIMP", 1.0), r(AYU, 2.0)]),
    ],
}

# ---------------------------------------------------------------------------
# 16. CONTROL DE CALIDAD Y ENSAYOS  (necesita 80)
# ---------------------------------------------------------------------------
CAP16 = {
    "01": [
        ("Toma de muestras de concreto para ensayo.", "ud",
         "Toma de muestras de concreto fresco en probetas normalizadas para ensayo de resistencia a compresión, con su identificación y curado.",
         [r(O1_ALB, 0.5), r(AYU, 0.25)]),
        ("Ensayo de compresión de probeta de concreto.", "ud",
         "Ensayo de resistencia a compresión de probeta de concreto en laboratorio, con emisión de informe.",
         [r(O1_ALB, 0.3), r(AYU, 0.15)]),
        ("Ensayo de asentamiento (slump) del concreto.", "ud",
         "Determinación del asentamiento del concreto fresco con el cono de Abrams, para verificar la trabajabilidad.",
         [r(O1_ALB, 0.2), r(AYU, 0.1)]),
        ("Ensayo de acero de refuerzo a tracción.", "ud",
         "Ensayo de tracción y doblado de muestra de acero de refuerzo, para verificar el límite elástico y la ductilidad.",
         [r(O1_ALB, 0.3), r(AYU, 0.15)]),
        ("Ensayo de compresión de bloques de mampostería.", "ud",
         "Ensayo de resistencia a compresión de bloque de mampostería, con emisión de informe.",
         [r(O1_ALB, 0.3), r(AYU, 0.15)]),
        ("Ensayo de mortero de pega.", "ud",
         "Ensayo de resistencia del mortero de pega de mampostería, con toma de muestra y laboratorio.",
         [r(O1_ALB, 0.3), r(AYU, 0.15)]),
        ("Ensayo de granulometría de agregados.", "ud",
         "Ensayo granulométrico de agregados (arena, gravilla) para verificar su idoneidad en la mezcla de concreto.",
         [r(O1_ALB, 0.3), r(AYU, 0.15)]),
        ("Control de recubrimiento de armadura.", "m²",
         "Verificación del recubrimiento de la armadura con detector magnético, para garantizar la protección del acero.",
         [r("MQ-DETECTOR", 0.05), r(O1_ALB, 0.1), r(AYU, 0.05)]),
        ("Ensayo de resistencia de piso de concreto.", "ud",
         "Ensayo no destructivo de la resistencia del concreto endurecido mediante esclerómetro, con informe.",
         [r("MQ-DETECTOR", 0.1), r(O1_ALB, 0.15), r(AYU, 0.08)]),
        ("Verificación de plomos y niveles de muros.", "m²",
         "Verificación de plomos, niveles y escuadras de muros y particiones, con nivel láser.",
         [r("MQ-NIVEL-LASER", 0.02), r(O1_ALB, 0.05), r(AYU, 0.03)]),
    ],
    "02": [
        ("Inspección visual de soldadura.", "m",
         "Inspección visual de cordones de soldadura, verificando continuidad, penetración y ausencia de defectos superficiales.",
         [r(O1_SOLD, 0.15), r(AYU, 0.08)]),
        ("Ensayo de líquidos penetrantes en soldadura.", "ud",
         "Ensayo de líquidos penetrantes para detección de fisuras superficiales en soldaduras, con informe.",
         [r(O1_SOLD, 0.3), r(AYU, 0.15)]),
        ("Ensayo de partículas magnéticas en soldadura.", "ud",
         "Ensayo de partículas magnéticas para detección de discontinuidades en soldaduras de acero, con informe.",
         [r(O1_SOLD, 0.3), r(AYU, 0.15)]),
        ("Ensayo ultrasónico de soldadura.", "ud",
         "Ensayo ultrasónico de soldaduras estructurales, para detección de defectos internos, con informe.",
         [r(O1_SOLD, 0.4), r(AYU, 0.2)]),
        ("Ensayo radiográfico de soldadura.", "ud",
         "Ensayo radiográfico de soldaduras de alta exigencia, para verificación de calidad interna, con informe.",
         [r(O1_SOLD, 0.5), r(AYU, 0.25)]),
        ("Prueba de carga de anclaje químico.", "ud",
         "Prueba de carga de anclaje químico o mecánico, para verificar la capacidad de fijación a la estructura.",
         [r(O1_ALB, 0.4), r(AYU, 0.2)]),
        ("Control de apriete de pernos estructurales.", "ud",
         "Verificación del par de apriete de los pernos de alta resistencia de la estructura, con llave dinamométrica.",
         [r(O1_ALB, 0.2), r(AYU, 0.1)]),
        ("Inspección dimensional de estructura metálica.", "m²",
         "Verificación dimensional y de plomos de la estructura metálica montada, con nivel láser.",
         [r("MQ-NIVEL-LASER", 0.02), r(O1_ALB, 0.08), r(AYU, 0.04)]),
        ("Ensayo de adherencia de anclaje de fachada.", "ud",
         "Ensayo de adherencia o extracción de anclajes de fachada y revestimientos, con informe.",
         [r(O1_ALB, 0.35), r(AYU, 0.18)]),
        ("Prueba de carga de estructura de techo.", "glb",
         "Prueba de carga puntual sobre estructura de techo para verificar su capacidad, con informe.",
         [r(O1_ALB, 1.0), r(AYU, 0.5)]),
    ],
    "03": [
        ("Prueba de estanqueidad de cubierta por inundación.", "m²",
         "Prueba de estanqueidad de cubierta plana por inundación controlada, con registro del nivel y revisión de puntos singulares.",
         [r(O1_ALB, 0.06), r(AYU, 0.05)]),
        ("Prueba de estanqueidad de baño o ducha.", "ud",
         "Prueba de estanqueidad de zona húmeda (baño, ducha) por inundación, para verificar la impermeabilización.",
         [r(O1_ALB, 0.5), r(AYU, 0.4)]),
        ("Prueba de estanqueidad de terraza.", "m²",
         "Prueba de estanqueidad de terraza por inundación, con revisión de desagües y remates.",
         [r(O1_ALB, 0.06), r(AYU, 0.05)]),
        ("Inspección de membrana impermeabilizante.", "m²",
         "Inspección visual de la membrana impermeabilizante, verificando solapes, remontes y puntos singulares.",
         [r(O1_ALB, 0.04), r(AYU, 0.03)]),
        ("Prueba de vacío en solapes de membrana.", "m",
         "Prueba de vacío sobre los solapes de la membrana impermeabilizante, para detectar defectos de soldadura.",
         [r("MQ-ASPIR", 0.03), r(O1_ALB, 0.08), r(AYU, 0.04)]),
        ("Prueba de estanqueidad de piscina.", "glb",
         "Prueba de estanqueidad de piscina por llenado controlado, con registro de pérdidas y revisión del vaso.",
         [r(O1_ALB, 2.0), r(AYU, 1.0)]),
        ("Prueba de estanqueidad de tanque.", "ud",
         "Prueba de estanqueidad de tanque o depósito por llenado, para verificar la ausencia de fugas.",
         [r(O1_ALB, 0.8), r(AYU, 0.4)]),
        ("Control de pendientes de evacuación.", "m²",
         "Verificación de las pendientes de evacuación de cubiertas y pisos húmedos, con nivel láser.",
         [r("MQ-NIVEL-LASER", 0.01), r(O1_ALB, 0.04), r(AYU, 0.02)]),
        ("Ensayo de impermeabilización de muro enterrado.", "m²",
         "Verificación de la impermeabilización de muro enterrado, con inspección y prueba puntual.",
         [r(O1_ALB, 0.05), r(AYU, 0.04)]),
        ("Informe de estanqueidad con protocolo.", "glb",
         "Emisión de informe de estanqueidad con protocolo de la prueba, para entrega a la propiedad.",
         [r(O1_ALB, 0.5), r(AYU, 0.25)]),
    ],
    "04": [
        ("Prueba hidrostática de tubería de agua.", "m",
         "Prueba hidrostática de la tubería de agua potable, con presión controlada y verificación de ausencia de fugas.",
         [r("MQ-HIDROLAV", 0.02), r(O1_PLO, 0.05), r(AYU, 0.03)]),
        ("Prueba de fugas de tubería de gas.", "m",
         "Prueba de estanqueidad de la tubería de gas con manómetro y jabón detector, para verificar la ausencia de fugas.",
         [r("MQ-DETECTOR", 0.03), r(O1_PLO, 0.06), r(AYU, 0.03)]),
        ("Prueba de desagüe por vaciado.", "ud",
         "Prueba de desagüe de aparato sanitario por vaciado controlado, para verificar la correcta evacuación.",
         [r(O1_PLO, 0.3), r(AYU, 0.15)]),
        ("Prueba de ventilación de desagüe.", "ud",
         "Verificación de la ventilación de la red de desagüe, para evitar sifonado y malos olores.",
         [r(O1_PLO, 0.3), r(AYU, 0.15)]),
        ("Prueba de presión de la red de agua.", "glb",
         "Prueba de presión general de la red de agua potable, con bomba de prueba y verificación de uniones.",
         [r("MQ-HIDROLAV", 0.2), r(O1_PLO, 0.6), r(AYU, 0.3)]),
        ("Verificación de pendientes de desagüe.", "m",
         "Verificación de las pendientes de la tubería de desagüe, con nivel láser, para asegurar la evacuación.",
         [r("MQ-NIVEL-LASER", 0.01), r(O1_PLO, 0.03), r(AYU, 0.02)]),
        ("Prueba de estanqueidad de trampa de grasa.", "ud",
         "Prueba de estanqueidad de la trampa de grasa, con llenado y verificación de ausencia de fugas.",
         [r(O1_PLO, 0.4), r(AYU, 0.2)]),
        ("Prueba de funcionamiento de válvulas.", "ud",
         "Verificación del funcionamiento de válvulas y llaves de corte, con apertura y cierre.",
         [r(O1_PLO, 0.2), r(AYU, 0.1)]),
        ("Informe de pruebas sanitarias.", "glb",
         "Emisión de informe de las pruebas sanitarias realizadas, con protocolo de resultados.",
         [r(O1_PLO, 0.5), r(AYU, 0.25)]),
        ("Prueba de descarga de inodoro y lavamanos.", "ud",
         "Prueba de descarga y funcionamiento de inodoro y lavamanos, verificando llenado, descarga y ausencia de fugas.",
         [r(O1_PLO, 0.2), r(AYU, 0.1)]),
    ],
    "05": [
        ("Medición de resistencia de puesta a tierra.", "ud",
         "Medición de la resistencia de puesta a tierra con telurómetro, para verificar el valor exigido por la norma.",
         [r("MQ-TELUROMETRO", 0.1), r(O1_ELE, 0.2), r(AYU, 0.1)]),
        ("Prueba de continuidad de conductores.", "ud",
         "Prueba de continuidad de los conductores de la instalación eléctrica, verificando la ausencia de cortes.",
         [r("MQ-DETECTOR", 0.05), r(O1_ELE, 0.15), r(AYU, 0.08)]),
        ("Prueba de aislamiento de conductores.", "ud",
         "Prueba de resistencia de aislamiento de los conductores, con megóhmetro, para verificar la ausencia de fugas.",
         [r("MQ-DETECTOR", 0.08), r(O1_ELE, 0.2), r(AYU, 0.1)]),
        ("Prueba de disparo de diferenciales.", "ud",
         "Prueba de disparo de los interruptores diferenciales con el botón de test, para verificar su funcionamiento.",
         [r(O1_ELE, 0.15), r(AYU, 0.08)]),
        ("Prueba de disparo de termomagnéticos.", "ud",
         "Verificación del disparo de los interruptores termomagnéticos, para comprobar su calibración.",
         [r(O1_ELE, 0.15), r(AYU, 0.08)]),
        ("Verificación de polaridad y neutro.", "ud",
         "Verificación de la polaridad y correcta conexión del neutro en los tomacorrientes, con comprobador.",
         [r("MQ-DETECTOR", 0.03), r(O1_ELE, 0.1), r(AYU, 0.05)]),
        ("Medición de tensión y frecuencia.", "glb",
         "Medición de la tensión y frecuencia de la acometida eléctrica, para verificar la calidad del suministro.",
         [r("MQ-DETECTOR", 0.05), r(O1_ELE, 0.1), r(AYU, 0.05)]),
        ("Prueba de iluminación de circuitos.", "ud",
         "Verificación del funcionamiento de los circuitos de iluminación, encendiendo y comprobando cada punto.",
         [r(O1_ELE, 0.1), r(AYU, 0.05)]),
        ("Prueba de puesta en marcha de tablero.", "ud",
         "Prueba de puesta en marcha del tablero de distribución, con verificación de cada circuito y su rotulado.",
         [r(O1_ELE, 0.4), r(AYU, 0.2)]),
        ("Informe de pruebas eléctricas.", "glb",
         "Emisión de informe de las pruebas eléctricas realizadas, con protocolo de mediciones.",
         [r(O1_ELE, 0.5), r(AYU, 0.25)]),
    ],
    "06": [
        ("Prueba de vacío de sistema de climatización.", "ud",
         "Prueba de vacío del circuito frigorífico de climatización, para eliminar humedad y verificar la estanqueidad.",
         [r("MQ-RECUP-GAS", 0.2), r(O1_AC, 0.5), r(AYU, 0.25)]),
        ("Prueba de presión de gas refrigerante.", "ud",
         "Prueba de presión del circuito frigorífico con nitrógeno, para detectar fugas antes de la carga.",
         [r("MQ-DETECTOR", 0.1), r(O1_AC, 0.4), r(AYU, 0.2)]),
        ("Carga de gas refrigerante.", "ud",
         "Carga de gas refrigerante del sistema de climatización, con báscula y verificación de presiones.",
         [r("MT-GAS-REFRIG", 0.5), r("MQ-RECUP-GAS", 0.1), r(O1_AC, 0.4), r(AYU, 0.2)]),
        ("Balanceo de caudales de ventilación.", "ud",
         "Balanceo de los caudales de ventilación, con anemómetro, para verificar la renovación de aire proyectada.",
         [r("MQ-DETECTOR", 0.1), r(O1_AC, 0.3), r(AYU, 0.15)]),
        ("Prueba de funcionamiento de extractores.", "ud",
         "Verificación del funcionamiento de extractores y ventiladores, con medición de caudal y ruido.",
         [r("MQ-DETECTOR", 0.05), r(O1_AC, 0.2), r(AYU, 0.1)]),
        ("Prueba de temperatura de impulsión.", "ud",
         "Medición de la temperatura de impulsión y retorno del sistema de climatización, para verificar el rendimiento.",
         [r("MQ-DETECTOR", 0.05), r(O1_AC, 0.2), r(AYU, 0.1)]),
        ("Limpieza de serpentines y filtros.", "ud",
         "Limpieza de serpentines y filtros del sistema de climatización, para asegurar el rendimiento.",
         [r("MT-QUIMICO-LIMP-AC", 0.5), r(O1_AC, 0.3), r(AYU, 0.15)]),
        ("Prueba de drenaje de condensados.", "ud",
         "Verificación del drenaje de condensados del sistema de climatización, para evitar reboses.",
         [r(O1_AC, 0.2), r(AYU, 0.1)]),
        ("Puesta en servicio de climatización con ajuste.", "glb",
         "Puesta en servicio del sistema de climatización completo, con ajuste de parámetros y verificación de rendimiento.",
         [r(O1_AC, 1.0), r(AYU, 0.5)]),
        ("Informe de puesta en marcha de climatización.", "glb",
         "Emisión de informe de puesta en marcha del sistema de climatización, con protocolo de resultados.",
         [r(O1_AC, 0.5), r(AYU, 0.25)]),
    ],
    "07": [
        ("Termografía infrarroja de fachada.", "m²",
         "Inspección termográfica de fachada para detectar puentes térmicos y pérdidas de energía, con informe.",
         [r("MQ-DETECTOR", 0.02), r(O1_ALB, 0.05), r(AYU, 0.03)]),
        ("Termografía infrarroja de cubierta.", "m²",
         "Inspección termográfica de cubierta para detectar filtraciones y defectos de aislamiento, con informe.",
         [r("MQ-DETECTOR", 0.02), r(O1_ALB, 0.05), r(AYU, 0.03)]),
        ("Termografía de instalación eléctrica.", "glb",
         "Inspección termográfica de la instalación eléctrica para detectar puntos calientes y conexiones defectuosas.",
         [r("MQ-DETECTOR", 0.1), r(O1_ELE, 0.3), r(AYU, 0.15)]),
        ("Medición de humedad de muros.", "m²",
         "Medición del contenido de humedad de muros con higrómetro, para diagnóstico de filtraciones o capilaridad.",
         [r("MQ-DETECTOR", 0.02), r(O1_ALB, 0.05), r(AYU, 0.03)]),
        ("Medición de humedad de piso.", "m²",
         "Medición del contenido de humedad del piso, para verificar la idoneidad antes de colocar revestimientos.",
         [r("MQ-DETECTOR", 0.02), r(O1_ALB, 0.04), r(AYU, 0.02)]),
        ("Detección de armadura y tuberías empotradas.", "m",
         "Detección de armadura, tuberías y conducciones empotradas con detector, para evitar perforaciones.",
         [r("MQ-DETECTOR", 0.03), r(O1_ALB, 0.05), r(AYU, 0.03)]),
        ("Inspección de fisuras y diagnóstico estructural.", "m",
         "Inspección de fisuras en elementos estructurales, con mapeo y diagnóstico de la causa.",
         [r("MQ-DETECTOR", 0.03), r(O1_ALB, 0.08), r(AYU, 0.04)]),
        ("Ensayo de esclerometría en elementos de concreto.", "ud",
         "Ensayo esclerométrico en elementos de concreto para estimar la resistencia, con informe.",
         [r("MQ-DETECTOR", 0.08), r(O1_ALB, 0.12), r(AYU, 0.06)]),
        ("Medición de espesor de recubrimiento.", "m²",
         "Medición del espesor de recubrimiento de la armadura con detector magnético, con informe.",
         [r("MQ-DETECTOR", 0.02), r(O1_ALB, 0.05), r(AYU, 0.03)]),
        ("Informe de diagnóstico no destructivo.", "glb",
         "Emisión de informe de diagnóstico no destructivo, con resultados de las inspecciones realizadas.",
         [r(O1_ALB, 0.5), r(AYU, 0.25)]),
    ],
    "08": [
        ("Protocolo de pruebas de puesta en marcha.", "glb",
         "Elaboración del protocolo de pruebas de puesta en marcha de las instalaciones, con firma de las partes.",
         [r(O1_ALB, 1.0), r(AYU, 0.5)]),
        ("Protocolo de entrega de instalaciones.", "glb",
         "Elaboración del protocolo de entrega de las instalaciones, con verificación final de cada sistema.",
         [r(O1_ALB, 1.0), r(AYU, 0.5)]),
        ("Documentación final de obra.", "glb",
         "Recopilación y entrega de la documentación final de obra, con planos, garantías y manuales.",
         [r(O1_ALB, 1.5), r(AYU, 0.75)]),
        ("Certificación de instalación eléctrica.", "glb",
         "Emisión de la certificación de la instalación eléctrica, con las mediciones y pruebas realizadas.",
         [r(O1_ELE, 1.0), r(AYU, 0.5)]),
        ("Certificación de instalación de gas.", "glb",
         "Emisión de la certificación de la instalación de gas, con la prueba de estanqueidad y cumplimiento.",
         [r(O1_PLO, 1.0), r(AYU, 0.5)]),
        ("Certificación de impermeabilización.", "glb",
         "Emisión de la certificación de la impermeabilización, con las pruebas de estanqueidad realizadas.",
         [r(O1_ALB, 0.8), r(AYU, 0.4)]),
        ("Manual de uso y mantenimiento.", "glb",
         "Elaboración del manual de uso y mantenimiento del inmueble, con las pautas de conservación.",
         [r(O1_ALB, 1.5), r(AYU, 0.75)]),
        ("Acta de recepción de obra.", "glb",
         "Elaboración del acta de recepción de obra, con el estado final y los pendientes.",
         [r(O1_ALB, 0.8), r(AYU, 0.4)]),
        ("Prueba integral de sistemas.", "glb",
         "Prueba integral de todos los sistemas de la obra, coordinando su funcionamiento conjunto.",
         [r(O1_ALB, 2.0), r(AYU, 1.0)]),
        ("Informe de conformidad con proyecto.", "glb",
         "Emisión del informe de conformidad con el proyecto, verificando que la obra se ajusta a lo contratado.",
         [r(O1_ALB, 1.2), r(AYU, 0.6)]),
    ],
}

# ---------------------------------------------------------------------------
# 17. SEGURIDAD Y SALUD EN OBRA  (necesita 49 para llegar a 60)
# ---------------------------------------------------------------------------
CAP17 = {
    "01": [
        ("Baranda de protección en perímetro de losa.", "m",
         "Colocación de baranda de protección en el perímetro de la losa, con guardacuerpos y rodapié, para prevenir caídas.",
         [r("MT-BARANDA-PROV", 1.05), r("MQ-TALADRO", 0.05), r(O1_ALB, 0.2), r(AYU, 0.12)]),
        ("Red de seguridad en hueco de escalera.", "m²",
         "Colocación de red de seguridad en hueco de escalera, con cuerdas de atado, para prevenir caídas.",
         [r("MT-RED-SEG", 1.05), r("MQ-TALADRO", 0.05), r(O1_ALB, 0.2), r(AYU, 0.12)]),
        ("Protección de hueco con tabla y barandilla.", "ud",
         "Protección de hueco con tabla resistente y barandilla, señalizada, para prevenir caídas.",
         [r("MT-BARANDA-PROV", 1.0), r("MT-MALLA-OBRA", 0.5), r(AYU, 0.3)]),
        ("Marquesina de protección de acceso.", "m²",
         "Colocación de marquesina de protección sobre el acceso a la obra, para evitar caída de objetos.",
         [r("MT-MALLA-OBRA", 1.1), r("MT-PERFIL-ACERO", 0.5), r(O1_ALB, 0.4), r(AYU, 0.24)]),
        ("Protección de borde con red vertical.", "m",
         "Colocación de red vertical de protección en el borde de losa, con sus soportes.",
         [r("MT-RED-SEG", 1.05), r("MQ-TALADRO", 0.05), r(O1_ALB, 0.2), r(AYU, 0.12)]),
        ("Cubrición de huecos de ascensor.", "m²",
         "Cubrición de huecos de ascensor con tabla y barandilla, para prevenir caídas durante la obra.",
         [r("MT-BARANDA-PROV", 0.8), r("MT-MALLA-OBRA", 0.5), r(AYU, 0.25)]),
    ],
    "02": [
        ("Dotación de casco de seguridad.", "ud",
         "Dotación de casco de seguridad para el personal de obra, conforme a la normativa.",
         [r("MT-EPP", 0.2), r(AYU, 0.02)]),
        ("Dotación de guantes y calzado de seguridad.", "ud",
         "Dotación de guantes y calzado de seguridad para el personal, conforme a la tarea.",
         [r("MT-EPP", 0.3), r(AYU, 0.02)]),
        ("Dotación de protección ocular y auditiva.", "ud",
         "Dotación de protección ocular (gafas) y auditiva (tapones) para trabajos con riesgo.",
         [r("MT-EPP", 0.2), r(AYU, 0.02)]),
        ("Dotación de mascarilla y protección respiratoria.", "ud",
         "Dotación de mascarilla y protección respiratoria para trabajos con polvo o vapores.",
         [r("MT-EPP", 0.15), r(AYU, 0.02)]),
        ("Dotación de chaleco reflectivo.", "ud",
         "Dotación de chaleco reflectivo para el personal, para su visibilidad en la obra.",
         [r("MT-EPP", 0.1), r(AYU, 0.02)]),
        ("Arnés de seguridad de cuerpo completo.", "ud",
         "Dotación de arnés de seguridad de cuerpo completo para trabajos en altura.",
         [r("MT-ARNES", 1.0), r(AYU, 0.02)]),
        ("Reposición de EPI durante la obra.", "glb",
         "Reposición de los equipos de protección individual consumidos o dañados durante la obra.",
         [r("MT-EPP", 2.0), r(AYU, 0.1)]),
    ],
    "03": [
        ("Señalización de riesgos en obra.", "ud",
         "Colocación de señalización de riesgos (caídas, golpes, electricidad) en la obra.",
         [r("MT-SENAL-OBRA", 1.0), r(AYU, 0.1)]),
        ("Delimitación con cinta de peligro.", "m",
         "Delimitación de zonas de riesgo con cinta de peligro y conos, para impedir el acceso.",
         [r("MT-SENAL-OBRA", 0.2), r(AYU, 0.05)]),
        ("Cierre perimetral de la obra.", "m",
         "Ejecución de cierre perimetral de la obra con malla de señalización, para control de accesos.",
         [r("MT-MALLA-OBRA", 1.5), r("MT-PERFIL-ACERO", 0.8), r(AYU, 0.3)]),
        ("Señalización de vías de evacuación.", "ud",
         "Colocación de señalización de vías de evacuación y salidas de emergencia en la obra.",
         [r("MT-SENAL-OBRA", 1.0), r(AYU, 0.08)]),
        ("Control de accesos a la obra.", "glb",
         "Habilitación de control de accesos a la obra, con registro de entrada del personal.",
         [r("MT-MALLA-OBRA", 0.5), r("MT-SENAL-OBRA", 0.3), r(AYU, 0.2)]),
        ("Iluminación de emergencia en obra.", "ud",
         "Colocación de iluminación de emergencia en las zonas de paso y evacuación de la obra.",
         [r("MT-LAMP-OBRA", 1.0), r(O1_ELE, 0.2), r(AYU, 0.1)]),
    ],
    "04": [
        ("Punto de anclaje de línea de vida.", "ud",
         "Ejecución de punto de anclaje para línea de vida en cubierta, con fijación a la estructura.",
         [r("MT-PERNO-ANCLA", 2.0), r("MT-EPOXI-ANCLA", 0.1), r("MQ-TALADRO", 0.1), r(O1_ALB, 0.3), r(AYU, 0.15)]),
        ("Eslinga y absorbedor de energía.", "ud",
         "Dotación de eslinga con absorbedor de energía para el amarre de arneses en trabajos en altura.",
         [r("MT-ARNES", 0.5), r(AYU, 0.02)]),
        ("Andamio con barandilla de protección.", "m²",
         "Montaje de andamio con barandilla de protección y rodapié, para trabajos en altura.",
         [r("MQ-ANDAMIO", 0.2), r(O1_ALB, 0.3), r(AYU, 0.18)]),
        ("Red de seguridad horizontal en cubierta.", "m²",
         "Colocación de red de seguridad horizontal bajo cubierta, para amortiguar caídas.",
         [r("MT-RED-SEG", 1.05), r("MQ-TALADRO", 0.05), r(O1_ALB, 0.22), r(AYU, 0.13)]),
        ("Escalera de mano con fijación.", "ud",
         "Colocación de escalera de mano con fijación y estabilización, para trabajos puntuales en altura.",
         [r("MT-APEO", 0.3), r(AYU, 0.15)]),
        ("Punto de anclaje en fachada.", "ud",
         "Ejecución de punto de anclaje en fachada para trabajos verticales, con fijación a la estructura.",
         [r("MT-PERNO-ANCLA", 2.0), r("MT-EPOXI-ANCLA", 0.1), r("MQ-TALADRO", 0.1), r(O1_ALB, 0.3), r(AYU, 0.15)]),
    ],
    "05": [
        ("Entibado de zanja.", "m²",
         "Entibado de zanja con tablones y puntales, para prevenir desprendimientos durante la excavación.",
         [r("MT-MADERA-ENTIB", 1.05), r(AYU, 0.3)]),
        ("Protección de borde de excavación.", "m",
         "Colocación de barandilla o señalización en el borde de la excavación, para prevenir caídas.",
         [r("MT-BARANDA-PROV", 1.0), r("MT-SENAL-OBRA", 0.2), r(AYU, 0.15)]),
        ("Ventilación de espacio confinado.", "glb",
         "Ventilación forzada de espacio confinado antes y durante el trabajo, para asegurar la calidad del aire.",
         [r("MQ-ASPIR", 0.3), r(AYU, 0.3)]),
        ("Medición de atmósfera en espacio confinado.", "glb",
         "Medición de la atmósfera de espacio confinado (oxígeno, gases), con detector, antes del acceso.",
         [r("MQ-DETECTOR", 0.15), r(AYU, 0.2)]),
        ("Protección de zanja con señalización nocturna.", "m",
         "Señalización y balizamiento nocturno de zanja abierta, para prevenir accidentes de tránsito.",
         [r("MT-SENAL-OBRA", 0.3), r(AYU, 0.1)]),
        ("Escalera de acceso a excavación.", "ud",
         "Colocación de escalera de acceso a la excavación, para evacuación segura del personal.",
         [r("MT-APEO", 0.3), r(AYU, 0.15)]),
    ],
    "06": [
        ("Extintor portátil de obra.", "ud",
         "Suministro y colocación de extintor portátil en la obra, con su señalización.",
         [r("MT-EXTINTOR", 1.0), r("MT-SENAL-OBRA", 0.2), r(AYU, 0.1)]),
        ("Extintor de CO2 para cuadro eléctrico.", "ud",
         "Suministro y colocación de extintor de CO2 junto al cuadro eléctrico de obra.",
         [r("MT-EXTINTOR", 1.0), r(AYU, 0.1)]),
        ("Señalización de extintores.", "ud",
         "Colocación de señalización de extintores y de los medios de extinción de la obra.",
         [r("MT-SENAL-OBRA", 0.3), r(AYU, 0.05)]),
        ("Retirada de material combustible.", "m²",
         "Retirada de material combustible de las zonas de trabajo, para reducir el riesgo de incendio.",
         [r("MT-SAC-ESC", 0.3), r(AYU, 0.2)]),
        ("Protección ignífuga de estructura de madera.", "m²",
         "Aplicación de tratamiento ignífugo sobre estructura de madera de obra, para mejorar su resistencia al fuego.",
         [r("MT-PIN-IGNFUGA", 0.15), r("MQ-RODILLO", 0.04), r(O1_PIN, 0.2), r(AYU, 0.1)]),
        ("Corte de oxicorte con pantalla de protección.", "glb",
         "Protección contra incendios en trabajos de oxicorte y soldadura, con pantalla y extintor próximo.",
         [r("MT-EXTINTOR", 0.2), r("MT-SENAL-OBRA", 0.2), r(AYU, 0.2)]),
    ],
    "07": [
        ("Adecuación de zona de vestuario y comedor.", "glb",
         "Adecuación de zona de vestuario y comedor de obra, con mobiliario y servicios básicos.",
         [r("MT-CASETA-BIEN", 1.0), r(AYU, 0.5)]),
        ("Baño químico portátil, por mes.", "ud",
         "Alquiler mensual de baño químico portátil, con su mantenimiento y limpieza.",
         [r("MQ-BANO-PORT", 1.0), r(AYU, 0.05)]),
        ("Agua potable para el personal.", "glb",
         "Suministro de agua potable para el personal de obra, conforme a la normativa de higiene.",
         [r("MT-AGUA-OBRA", 0.5), r(AYU, 0.1)]),
        ("Botiquín de primeros auxilios.", "ud",
         "Suministro y dotación de botiquín de primeros auxilios de obra, con su reposición.",
         [r("MT-BOTIQUIN", 1.0), r(AYU, 0.05)]),
        ("Reposición de botiquín de primeros auxilios.", "glb",
         "Reposición del material consumido del botiquín de primeros auxilios durante la obra.",
         [r("MT-BOTIQUIN", 0.5), r(AYU, 0.05)]),
        ("Camilla de evacuación.", "ud",
         "Suministro de camilla de evacuación para la obra, con su ubicación señalizada.",
         [r("MT-BOTIQUIN", 0.5), r(AYU, 0.1)]),
    ],
    "08": [
        ("Charla de inducción en seguridad.", "glb",
         "Impartición de charla de inducción en seguridad al personal que ingresa a la obra.",
         [r(O1_ALB, 1.0), r(AYU, 0.5)]),
        ("Formación específica en trabajos en altura.", "glb",
         "Formación específica al personal para trabajos en altura, con prácticas de uso de EPI.",
         [r(O1_ALB, 2.0), r(AYU, 1.0)]),
        ("Formación en manejo de equipos.", "glb",
         "Formación al personal en el manejo seguro de equipos y herramientas de obra.",
         [r(O1_ALB, 1.5), r(AYU, 0.75)]),
        ("Plan de seguridad y salud de la obra.", "glb",
         "Elaboración del plan de seguridad y salud de la obra, con evaluación de riesgos.",
         [r(O1_ALB, 2.0), r(AYU, 1.0)]),
        ("Documentación preventiva y registros.", "glb",
         "Elaboración de la documentación preventiva y registros de seguridad de la obra.",
         [r(O1_ALB, 1.5), r(AYU, 0.75)]),
        ("Inspección de seguridad periódica.", "glb",
         "Inspección de seguridad periódica de la obra, con emisión de informe de observaciones.",
         [r(O1_ALB, 1.0), r(AYU, 0.5)]),
    ],
}

# ---------------------------------------------------------------------------
# 18. REHABILITACIÓN ENERGÉTICA  (necesita 100)
# ---------------------------------------------------------------------------
CAP18 = {
    "01": [
        ("Evaluación energética de la vivienda.", "glb",
         "Evaluación energética de la vivienda, con inspección de la envolvente, instalaciones y consumos, y emisión de informe.",
         [r("MQ-DETECTOR", 0.3), r(O1_ALB, 3.0), r(AYU, 1.5)]),
        ("Diagnóstico de puentes térmicos.", "glb",
         "Diagnóstico de puentes térmicos de la envolvente con termografía, para identificar pérdidas de energía.",
         [r("MQ-DETECTOR", 0.4), r(O1_ALB, 2.0), r(AYU, 1.0)]),
        ("Auditoría de consumos energéticos.", "glb",
         "Auditoría de los consumos energéticos de la vivienda, con análisis de facturas y propuesta de mejora.",
         [r(O1_ALB, 2.0), r(AYU, 1.0)]),
        ("Medición de infiltraciones de aire.", "glb",
         "Medición de las infiltraciones de aire de la vivienda, para evaluar la estanqueidad de la envolvente.",
         [r("MQ-DETECTOR", 0.3), r(O1_ALB, 1.5), r(AYU, 0.75)]),
        ("Informe de certificación energética.", "glb",
         "Emisión del informe de certificación energética de la vivienda, con la calificación obtenida.",
         [r(O1_ALB, 1.5), r(AYU, 0.75)]),
        ("Estudio de viabilidad de energías renovables.", "glb",
         "Estudio de viabilidad de incorporación de energías renovables, con análisis de radiación y consumos.",
         [r(O1_ELE, 1.5), r(AYU, 0.75)]),
        ("Medición de espesores de aislamiento existente.", "m²",
         "Medición de los espesores de aislamiento existentes en la envolvente, con detector.",
         [r("MQ-DETECTOR", 0.02), r(O1_ALB, 0.05), r(AYU, 0.03)]),
        ("Inspección de carpintería y vidrios.", "ud",
         "Inspección del estado de la carpintería y vidrios, para evaluar su contribución a las pérdidas térmicas.",
         [r(O1_ALB, 0.4), r(AYU, 0.2)]),
        ("Levantamiento de la envolvente térmica.", "m²",
         "Levantamiento de la envolvente térmica de la vivienda, con medición de superficies y composición.",
         [r("MQ-NIVEL-LASER", 0.02), r(O1_ALB, 0.08), r(AYU, 0.04)]),
        ("Propuesta de medidas de rehabilitación energética.", "glb",
         "Elaboración de propuesta de medidas de rehabilitación energética, con estimación de ahorros.",
         [r(O1_ALB, 2.0), r(AYU, 1.0)]),
        ("Seguimiento y medición de ahorro energético.", "glb",
         "Seguimiento y medición del ahorro energético tras la rehabilitación, con comparación de consumos.",
         [r(O1_ELE, 1.5), r(AYU, 0.75)]),
    ],
    "02": [
        ("Aislamiento de fachada con poliestireno extruido.", "m²",
         "Colocación de panel de poliestireno extruido sobre fachada, fijado y con capa de protección.",
         [r("MT-POLIESTIRENO-EXT", 1.05), r("MT-MALLA-FACH", 1.05), r("MQ-TALADRO", 0.06), r(O1_ALB, 0.4), r(AYU, 0.32)]),
        ("Aislamiento de fachada con lana de roca.", "m²",
         "Colocación de panel de lana de roca sobre fachada, fijado y con capa de protección.",
         [r("MT-LANA-ROCA", 1.05), r("MT-MALLA-FACH", 1.05), r("MQ-TALADRO", 0.06), r(O1_ALB, 0.4), r(AYU, 0.32)]),
        ("SATE de fachada con poliestireno expandido.", "m²",
         "Sistema de aislamiento térmico exterior (SATE) de fachada con poliestireno expandido, malla y mortero.",
         [r("MT-AISL-TERM", 1.05), r("MT-MALLA-FACH", 1.1), r("MT-MOR-FRISO", 0.01), r("MQ-MEZCL", 0.04), r(O1_ALB, 0.5), r(AYU, 0.4)]),
        ("Fachada ventilada con subestructura y aislamiento.", "m²",
         "Ejecución de fachada ventilada con subestructura metálica y aislamiento térmico, con cámara de aire.",
         [r("MT-SUBESTRUCTURA", 1.0), r("MT-LANA-ROCA", 1.05), r("MQ-TALADRO", 0.08), r(O1_MON, 0.5), r(AYU, 0.4)]),
        ("Revestimiento de fachada con panel composite.", "m²",
         "Colocación de panel composite sobre fachada, con fijación mecánica, para mejorar el aislamiento y la estética.",
         [r("MT-PLACA-FACHADA", 1.05), r("MT-SUBESTRUCTURA", 1.0), r("MQ-TALADRO", 0.08), r(O1_MON, 0.5), r(AYU, 0.4)]),
        ("Aislamiento de fachada con lana mineral proyectada.", "m²",
         "Proyección de lana mineral aislante sobre fachada, para relleno de cámaras y mejora térmica.",
         [r("MT-LANA-ROCA", 1.1), r("MQ-PROYECT-MORT", 0.05), r(O1_ALB, 0.4), r(AYU, 0.32)]),
        ("Inyección de aislamiento en cámara de fachada.", "m²",
         "Inyección de aislamiento en la cámara de aire de la fachada, para mejorar la resistencia térmica.",
         [r("MT-LANA-ROCA", 1.0), r("MQ-INYECTORA", 0.04), r(O1_ALB, 0.35), r(AYU, 0.28)]),
        ("Refuerzo de aislamiento en petos y cantos.", "m",
         "Colocación de refuerzo de aislamiento en petos, cantos y puntos singulares de la fachada.",
         [r("MT-POLIESTIRENO-EXT", 0.5), r("MT-MALLA-FACH", 0.6), r("MQ-TALADRO", 0.03), r(O1_ALB, 0.25), r(AYU, 0.2)]),
        ("Remate de aislamiento en esquinas y juntas.", "m",
         "Ejecución de remates de aislamiento en esquinas, juntas y encuentros de la fachada.",
         [r("MT-MALLA-ESQ", 1.05), r("MT-MOR-FRISO", 0.005), r(O1_ALB, 0.2), r(AYU, 0.16)]),
        ("Tratamiento de puentes térmicos de fachada.", "m",
         "Tratamiento de los puentes térmicos de fachada con piezas de aislamiento en los puntos singulares.",
         [r("MT-POLIESTIRENO-EXT", 0.4), r("MT-MALLA-FACH", 0.5), r(O1_ALB, 0.22), r(AYU, 0.18)]),
        ("Acabado de fachada aislada con mortero.", "m²",
         "Acabado de fachada aislada con mortero de protección y malla, listo para el revestimiento final.",
         [r("MT-MOR-FRISO", 0.02), r("MT-MALLA-FACH", 1.05), r("MQ-MEZCL", 0.03), r(O1_ALB, 0.35), r(AYU, 0.28)]),
    ],
    "03": [
        ("Aislamiento de techo con poliestireno extruido.", "m²",
         "Colocación de panel de poliestireno extruido sobre el techo, para reducir las pérdidas térmicas.",
         [r("MT-POLIESTIRENO-EXT", 1.05), r(O1_ALB, 0.15), r(AYU, 0.12)]),
        ("Aislamiento de techo con lana de roca.", "m²",
         "Colocación de panel de lana de roca sobre el techo, para mejora del aislamiento térmico y acústico.",
         [r("MT-LANA-ROCA", 1.05), r(O1_ALB, 0.15), r(AYU, 0.12)]),
        ("Aislamiento de cubierta con manta reflectiva.", "m²",
         "Colocación de manta reflectiva de doble burbuja bajo cubierta, para reducir la ganancia de calor.",
         [r("MT-AISL-REFLECT", 1.05), r("MQ-TALADRO", 0.03), r(O1_ALB, 0.12), r(AYU, 0.1)]),
        ("Aislamiento de cubierta plana con lana mineral.", "m²",
         "Colocación de panel de lana mineral sobre cubierta plana, previo a la impermeabilización.",
         [r("MT-PYL-LANA", 1.05), r(O1_ALB, 0.15), r(AYU, 0.12)]),
        ("Aislamiento de techo entre viguetas.", "m²",
         "Colocación de aislamiento entre las viguetas del techo, para eliminar puentes térmicos.",
         [r("MT-LANA-ROCA", 1.05), r(O1_ALB, 0.2), r(AYU, 0.16)]),
        ("Barrera de vapor en cubierta.", "m²",
         "Colocación de barrera de vapor bajo el aislamiento de cubierta, para evitar condensaciones.",
         [r("MT-POLIET", 1.05), r("MT-CINTA-ENM", 0.02), r(O1_ALB, 0.08), r(AYU, 0.06)]),
        ("Aislamiento de techo con celulosa insuflada.", "m²",
         "Insulfado de celulosa aislante en el espacio bajo cubierta, para mejora térmica y acústica.",
         [r("MT-LANA-ROCA", 1.0), r("MQ-PROYECT-MORT", 0.04), r(O1_ALB, 0.3), r(AYU, 0.24)]),
        ("Refuerzo de aislamiento en cumbrera.", "m",
         "Colocación de refuerzo de aislamiento en la cumbrera de la cubierta, para eliminar el puente térmico.",
         [r("MT-POLIESTIRENO-EXT", 0.4), r(O1_ALB, 0.2), r(AYU, 0.16)]),
        ("Aislamiento de lucernario o claraboya.", "ud",
         "Colocación de aislamiento en el perímetro del lucernario o claraboya, para reducir las pérdidas.",
         [r("MT-POLIESTIRENO-EXT", 0.5), r("MT-SILICONA-EST", 0.05), r(O1_ALB, 0.3), r(AYU, 0.24)]),
        ("Cubierta fría con aislamiento y ventilación.", "m²",
         "Ejecución de cubierta fría con aislamiento y cámara ventilada, para reducir la ganancia de calor.",
         [r("MT-LANA-ROCA", 1.05), r("MT-REJILLA-VENT", 0.2), r(O1_ALB, 0.35), r(AYU, 0.28)]),
        ("Aislamiento de techo de entrepiso no acondicionado.", "m²",
         "Colocación de aislamiento en el techo que separa espacios acondicionados de no acondicionados.",
         [r("MT-POLIESTIRENO-EXT", 1.05), r(O1_ALB, 0.15), r(AYU, 0.12)]),
    ],
    "04": [
        ("Aislamiento de piso con poliestireno.", "m²",
         "Colocación de panel de poliestireno bajo el piso, para reducir las pérdidas térmicas al terreno.",
         [r("MT-POLIESTIRENO-EXT", 1.05), r(O1_ALB, 0.12), r(AYU, 0.1)]),
        ("Aislamiento de piso con manta reflectiva.", "m²",
         "Colocación de manta reflectiva bajo el piso, para mejorar el confort y reducir pérdidas.",
         [r("MT-AISL-REFLECT", 1.05), r(O1_ALB, 0.1), r(AYU, 0.08)]),
        ("Aislamiento perimetral de piso.", "m",
         "Colocación de aislamiento en el perímetro del piso, para evitar el puente térmico con el terreno.",
         [r("MT-POLIESTIRENO-EXT", 0.3), r(O1_ALB, 0.15), r(AYU, 0.12)]),
        ("Aislamiento de entrepiso entre viviendas.", "m²",
         "Colocación de aislamiento en el entrepiso entre viviendas, para mejora térmica y acústica.",
         [r("MT-LANA-ROCA", 1.05), r(O1_ALB, 0.15), r(AYU, 0.12)]),
        ("Aislamiento de piso sobre cámara sanitaria.", "m²",
         "Colocación de aislamiento bajo el piso sobre cámara sanitaria, para evitar pérdidas al exterior.",
         [r("MT-POLIESTIRENO-EXT", 1.05), r(O1_ALB, 0.15), r(AYU, 0.12)]),
        ("Aislamiento de piso de ático.", "m²",
         "Colocación de aislamiento en el piso del ático, para reducir la pérdida de calor por el techo.",
         [r("MT-LANA-ROCA", 1.05), r(O1_ALB, 0.15), r(AYU, 0.12)]),
        ("Banda perimetral en encuentro piso-muro.", "m",
         "Colocación de banda perimetral elástica en el encuentro piso-muro, para eliminar el puente acústico y térmico.",
         [r("MT-PER-BANDA", 1.05), r(O1_ALB, 0.06), r(AYU, 0.05)]),
        ("Aislamiento de piso con panel rígido de lana.", "m²",
         "Colocación de panel rígido de lana mineral bajo el piso, para aislamiento térmico y acústico.",
         [r("MT-PYL-LANA", 1.05), r(O1_ALB, 0.12), r(AYU, 0.1)]),
        ("Tratamiento de puente térmico en canto de losa.", "m",
         "Tratamiento del puente térmico en el canto de la losa, con pieza de aislamiento.",
         [r("MT-POLIESTIRENO-EXT", 0.3), r(O1_ALB, 0.18), r(AYU, 0.14)]),
        ("Aislamiento de piso de garaje.", "m²",
         "Colocación de aislamiento en el piso del garaje, para reducir la pérdida térmica al exterior.",
         [r("MT-POLIESTIRENO-EXT", 1.05), r(O1_ALB, 0.15), r(AYU, 0.12)]),
        ("Regularización con mortero aislante.", "m²",
         "Regularización del piso con mortero aligerado aislante, para mejorar la resistencia térmica.",
         [r("MT-MOR-FRISO", 0.03), r("MT-ANIME-ALIV", 1.0), r("MQ-MEZCL", 0.03), r(O1_ALB, 0.3), r(AYU, 0.24)]),
    ],
    "05": [
        ("Sustitución de ventana por doble acristalamiento.", "m²",
         "Sustitución de ventana por doble acristalamiento con cámara de aire, para reducir las pérdidas térmicas. El vidrio lo elige el cliente.",
         [r("MT-VIDRIO-DOBLE", 1.05), r("MT-SILICONA-EST", 0.05), r("MQ-TALADRO", 0.1), r(O1_VIDR, 0.6), r(AYU, 0.3)],
         {"tipo": "Doble acristalamiento elegido por el cliente", "unidad": "m²", "consumo": 1.0, "nota": "La partida cubre la colocación. El vidrio se toma del catálogo de productos."}),
        ("Sustitución de ventana por vidrio templado.", "m²",
         "Sustitución de ventana por vidrio templado de seguridad, para mejora térmica y de resistencia. El vidrio lo elige el cliente.",
         [r("MT-VIDRIO-TEMP", 1.05), r("MT-SILICONA-EST", 0.05), r("MQ-TALADRO", 0.1), r(O1_VIDR, 0.6), r(AYU, 0.3)],
         {"tipo": "Vidrio templado elegido por el cliente", "unidad": "m²", "consumo": 1.0, "nota": "La partida cubre la colocación. El vidrio se toma del catálogo de productos."}),
        ("Sustitución de ventana por vidrio de control solar.", "m²",
         "Sustitución de ventana por vidrio de control solar, para reducir la ganancia térmica. El vidrio lo elige el cliente.",
         [r("MT-VIDRIO-DOBLE", 1.05), r("MT-SILICONA-EST", 0.05), r("MQ-TALADRO", 0.1), r(O1_VIDR, 0.6), r(AYU, 0.3)],
         {"tipo": "Vidrio de control solar elegido por el cliente", "unidad": "m²", "consumo": 1.0, "nota": "La partida cubre la colocación. El vidrio se toma del catálogo de productos."}),
        ("Sustitución de ventana con marco aislante.", "m²",
         "Sustitución de ventana con marco de ruptura de puente térmico y doble acristalamiento. El sistema lo elige el cliente.",
         [r("MT-PERFIL-ALUM", 1.0), r("MT-VIDRIO-DOBLE", 1.05), r("MQ-TALADRO", 0.12), r(O1_VIDR, 0.7), r(AYU, 0.35)],
         {"tipo": "Ventana con marco aislante elegida por el cliente", "unidad": "m²", "consumo": 1.0, "nota": "La partida cubre la colocación. La ventana se toma del catálogo de productos."}),
        ("Sellado perimetral de ventanas.", "m",
         "Sellado del perímetro de las ventanas, para eliminar las infiltraciones de aire.",
         [r("MT-SELLA-ELAST", 0.06), r("MT-SILICONA-EST", 0.03), r(O1_ALB, 0.12), r(AYU, 0.1)]),
        ("Sustitución de junta de estanqueidad de ventana.", "m",
         "Sustitución de la junta de estanqueidad de las ventanas, para mejorar la hermeticidad.",
         [r("MT-SILICONA-EST", 0.03), r(O1_ALB, 0.1), r(AYU, 0.08)]),
        ("Calafateado de carpintería exterior.", "m",
         "Calafateado y sellado de la carpintería exterior, para eliminar infiltraciones de aire y agua.",
         [r("MT-SELLA-ELAST", 0.06), r(O1_ALB, 0.12), r(AYU, 0.1)]),
        ("Persiana aislante con cajón estanco.", "m²",
         "Colocación de persiana aislante con cajón estanco, para mejorar el aislamiento del hueco. La persiana la elige el cliente.",
         [r("MT-PERSIANA-ALU", 1.05), r("MT-CAJON-PERS", 0.8), r("MQ-TALADRO", 0.1), r(O1_MON, 0.5), r(AYU, 0.25)],
         {"tipo": "Persiana aislante elegida por el cliente", "unidad": "m²", "consumo": 1.0, "nota": "La partida cubre la colocación. La persiana se toma del catálogo de productos."}),
        ("Sustitución de puerta exterior con aislamiento.", "ud",
         "Sustitución de puerta exterior por una con núcleo aislante, para reducir las pérdidas. La puerta la elige el cliente.",
         [r("MT-MARCO-PUERTA", 1.0), r("MT-SELLA-ELAST", 0.08), r("MQ-TALADRO", 0.2), r(O1_CARPM, 1.0), r(AYU, 0.5)],
         {"tipo": "Puerta exterior aislante elegida por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre la instalación. La puerta se toma del catálogo de productos."}),
        ("Burlete de estanqueidad en puertas.", "m",
         "Colocación de burlete de estanqueidad en el perímetro de las puertas exteriores, para reducir infiltraciones.",
         [r("MT-SELLA-ELAST", 0.04), r(O1_ALB, 0.08), r(AYU, 0.06)]),
        ("Ventana de doble acristalamiento con gas argón.", "m²",
         "Sustitución por ventana de doble acristalamiento con gas argón y marco aislante, de altas prestaciones. El sistema lo elige el cliente.",
         [r("MT-VIDRIO-DOBLE", 1.05), r("MT-PERFIL-ALUM", 1.0), r("MQ-TALADRO", 0.12), r(O1_VIDR, 0.7), r(AYU, 0.35)],
         {"tipo": "Ventana de altas prestaciones elegida por el cliente", "unidad": "m²", "consumo": 1.0, "nota": "La partida cubre la colocación. La ventana se toma del catálogo de productos."}),
    ],
    "06": [
        ("Toldo exterior de protección solar.", "m²",
         "Colocación de toldo exterior de protección solar, para reducir la ganancia térmica. El toldo lo elige el cliente.",
         [r("MT-TOLDO", 1.05), r("MT-PERNO-ANCLA", 1.0), r("MQ-TALADRO", 0.1), r(O1_MON, 0.4), r(AYU, 0.2)],
         {"tipo": "Toldo exterior elegido por el cliente", "unidad": "m²", "consumo": 1.0, "nota": "La partida cubre la colocación. El toldo se toma del catálogo de productos."}),
        ("Persiana enrollable de aluminio para control solar.", "m²",
         "Colocación de persiana enrollable de aluminio para control solar. La persiana la elige el cliente.",
         [r("MT-PERSIANA-ALU", 1.05), r("MT-CAJON-PERS", 0.8), r("MQ-TALADRO", 0.1), r(O1_MON, 0.5), r(AYU, 0.25)],
         {"tipo": "Persiana enrollable elegida por el cliente", "unidad": "m²", "consumo": 1.0, "nota": "La partida cubre la colocación. La persiana se toma del catálogo de productos."}),
        ("Celosía o romanilla de sombreado.", "m²",
         "Colocación de celosía o romanilla de aluminio para sombreado, reduciendo la ganancia solar.",
         [r("MT-CELOSIA", 1.05), r("MT-PERFIL-REMATE", 0.5), r("MQ-TALADRO", 0.08), r(O1_MON, 0.4), r(AYU, 0.2)]),
        ("Pérgola de sombreado exterior.", "m²",
         "Ejecución de pérgola de sombreado exterior, para proteger del sol las zonas acristaladas.",
         [r("MT-MADERA-PERGOLA", 2.0), r("MT-PRESERV-MAD", 0.04), r("MT-PERNO-ANCLA", 1.5), r("MQ-TALADRO", 0.12), r(O1_CARPM, 0.8), r(AYU, 0.64)]),
        ("Lámina de control solar en vidrios.", "m²",
         "Aplicación de lámina de control solar sobre los vidrios, para reducir la ganancia térmica.",
         [r("MT-ANTI-GRAFFITI", 0.1), r(O1_VIDR, 0.3), r(AYU, 0.15)]),
        ("Cortina térmica interior.", "m²",
         "Colocación de cortina térmica interior, para mejorar el aislamiento del hueco.",
         [r("MT-PERFIL-CORTINERO", 0.8), r("MQ-TALADRO", 0.06), r(O1_MON, 0.3), r(AYU, 0.15)]),
        ("Motorización de persiana existente.", "ud",
         "Motorización de persiana existente, con conexión eléctrica y programación. El motor lo elige el cliente.",
         [r("MT-DOM-PERSIANA", 1.0), r("MT-ELE-CABLE", 2.0), r("MQ-TALADRO", 0.2), r(O1_ELE, 0.6), r(AYU, 0.3)],
         {"tipo": "Motor de persiana elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El motor se toma del catálogo de productos."}),
        ("Automatización de toldo con sensor solar.", "ud",
         "Automatización de toldo con sensor solar, para accionamiento automático. El sistema lo elige el cliente.",
         [r("MT-DOM-SENSOR-LUZ", 1.0), r("MT-ELE-CABLE", 2.0), r("MQ-TALADRO", 0.2), r(O1_ELE, 0.6), r(AYU, 0.3)],
         {"tipo": "Sistema de automatización elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El sistema se toma del catálogo de productos."}),
        ("Marquesina de sombreado.", "m²",
         "Ejecución de marquesina de sombreado sobre ventanas, para reducir la ganancia solar directa.",
         [r("MT-POLICARB", 1.05), r("MT-PERFIL-ACERO", 1.0), r("MT-TORN-TECHO", 4.0), r("MQ-TALADRO", 0.08), r(O1_MON, 0.5), r(AYU, 0.4)]),
        ("Vegetación de sombreado de fachada.", "m",
         "Plantación de vegetación trepadora para sombreado de fachada, reduciendo la ganancia térmica. Las plantas las elige el cliente.",
         [r("MT-TIERRA-ABON", 0.02), r(O1_JARD, 0.3), r(AYU, 0.24)],
         {"tipo": "Plantas trepadoras elegidas por el cliente", "unidad": "m", "consumo": 2.0, "nota": "La partida cubre la siembra. Las plantas se toman del catálogo de productos."}),
        ("Película reflectiva en cubierta.", "m²",
         "Aplicación de película reflectiva sobre cubierta, para reducir la ganancia de calor solar.",
         [r("MT-AISL-REFLECT", 1.05), r(O1_ALB, 0.1), r(AYU, 0.08)]),
    ],
    "07": [
        ("Sustitución de equipo de climatización eficiente.", "ud",
         "Sustitución de equipo de climatización por uno de alta eficiencia, con conexión y puesta en marcha. El equipo lo elige el cliente.",
         [r("MT-TUB-FRIGO", 4.0), r("MT-SOPORTE-AC", 1.0), r("MQ-TALADRO", 0.3), r(O1_AC, 2.0), r(AYU, 1.0)],
         {"tipo": "Equipo de climatización eficiente elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El equipo se toma del catálogo de productos."}),
        ("Termostato programable.", "ud",
         "Instalación de termostato programable, con conexión y programación. El termostato lo elige el cliente.",
         [r("MT-DOM-TERMOSTATO", 1.0), r("MT-ELE-CABLE", 1.0), r("MQ-TALADRO", 0.15), r(O1_ELE, 0.5), r(AYU, 0.25)],
         {"tipo": "Termostato programable elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El termostato se toma del catálogo de productos."}),
        ("Limpieza y mantenimiento de climatización.", "ud",
         "Limpieza y mantenimiento del sistema de climatización, con limpieza de filtros y serpentines.",
         [r("MT-QUIMICO-LIMP-AC", 0.5), r(O1_AC, 0.4), r(AYU, 0.2)]),
        ("Aislamiento de conductos de climatización.", "m",
         "Aislamiento de los conductos de climatización, para evitar pérdidas de energía.",
         [r("MT-AISL-TERM", 0.5), r("MT-CINTA-ENM", 0.1), r(O1_AC, 0.2), r(AYU, 0.16)]),
        ("Ventilación mecánica controlada.", "ud",
         "Instalación de sistema de ventilación mecánica controlada, con recuperador de calor. El equipo lo elige el cliente.",
         [r("MT-DUCTO-VENT", 3.0), r("MT-REJILLA-VENT", 2.0), r("MQ-TALADRO", 0.25), r(O1_AC, 1.5), r(AYU, 0.75)],
         {"tipo": "Sistema de ventilación mecánica elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El equipo se toma del catálogo de productos."}),
        ("Recuperador de calor.", "ud",
         "Instalación de recuperador de calor en el sistema de ventilación. El equipo lo elige el cliente.",
         [r("MT-DUCTO-VENT", 2.0), r("MT-REJILLA-VENT", 2.0), r("MQ-TALADRO", 0.2), r(O1_AC, 1.0), r(AYU, 0.5)],
         {"tipo": "Recuperador de calor elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El equipo se toma del catálogo de productos."}),
        ("Sustitución de ductos de ventilación.", "m",
         "Sustitución de ductos de ventilación, para mejorar la eficiencia del sistema.",
         [r("MT-DUCTO-VENT", 1.05), r("MT-REJILLA-VENT", 0.3), r("MQ-TALADRO", 0.05), r(O1_AC, 0.3), r(AYU, 0.24)]),
        ("Ventilación natural con rejillas regulables.", "ud",
         "Instalación de rejillas de ventilación regulables, para aprovechar la ventilación natural.",
         [r("MT-REJILLA-VENT", 1.0), r("MQ-TALADRO", 0.08), r(O1_MON, 0.25), r(AYU, 0.2)]),
        ("Zonificación del sistema de climatización.", "ud",
         "Zonificación del sistema de climatización, con compuertas motorizadas y control. El sistema lo elige el cliente.",
         [r("MT-DUCTO-VENT", 1.5), r("MT-DOM-ACTUADOR", 1.0), r("MQ-TALADRO", 0.2), r(O1_AC, 0.8), r(AYU, 0.4)],
         {"tipo": "Sistema de zonificación elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El sistema se toma del catálogo de productos."}),
        ("Calibración y balanceo del sistema.", "glb",
         "Calibración y balanceo del sistema de climatización, para asegurar el rendimiento óptimo.",
         [r("MQ-DETECTOR", 0.15), r(O1_AC, 0.6), r(AYU, 0.3)]),
        ("Sellado de conductos de climatización.", "m",
         "Sellado de las uniones de los conductos de climatización, para evitar fugas de aire.",
         [r("MT-CINTA-ENM", 0.15), r("MT-SELLA-ELAST", 0.02), r(O1_AC, 0.15), r(AYU, 0.12)]),
    ],
    "08": [
        ("Sustitución de luminarias por LED.", "ud",
         "Sustitución de luminarias por LED de alta eficiencia, con conexión. La luminaria la elige el cliente.",
         [r("MT-ELE-CABLE", 1.0), r("MT-ELE-CAJA", 1.0), r("MQ-TALADRO", 0.15), r(O1_ELE, 0.5), r(AYU, 0.25)],
         {"tipo": "Luminaria LED elegida por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. La luminaria se toma del catálogo de productos."}),
        ("Iluminación LED con sensor de presencia.", "ud",
         "Instalación de luminaria LED con sensor de presencia, para ahorro en zonas de paso. La luminaria la elige el cliente.",
         [r("MT-DOM-SENSOR-MOV", 1.0), r("MT-ELE-CABLE", 1.0), r("MQ-TALADRO", 0.15), r(O1_ELE, 0.5), r(AYU, 0.25)],
         {"tipo": "Luminaria LED con sensor elegida por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. La luminaria se toma del catálogo de productos."}),
        ("Tira LED de iluminación eficiente.", "m",
         "Colocación de tira LED de iluminación eficiente, con fuente y perfil. La tira la elige el cliente.",
         [r("MT-CINTA-LED", 1.05), r("MT-ELE-CABLE", 1.0), r("MQ-TALADRO", 0.12), r(O1_ELE, 0.35), r(AYU, 0.18)],
         {"tipo": "Tira LED elegida por el cliente", "unidad": "m", "consumo": 1.0, "nota": "La partida cubre solo la instalación. La tira LED se toma del catálogo de productos."}),
        ("Regulación de iluminación con dimmer.", "ud",
         "Instalación de regulador (dimmer) de iluminación, para ajustar el consumo. El regulador lo elige el cliente.",
         [r("MT-DOM-DIMMER", 1.0), r("MT-ELE-CABLE", 1.0), r("MQ-TALADRO", 0.15), r(O1_ELE, 0.4), r(AYU, 0.2)],
         {"tipo": "Regulador de iluminación elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El regulador se toma del catálogo de productos."}),
        ("Sensor de luz natural para iluminación.", "ud",
         "Instalación de sensor de nivel de luz, para regular la iluminación según la luz natural. El sensor lo elige el cliente.",
         [r("MT-DOM-SENSOR-LUZ", 1.0), r("MT-ELE-CABLE", 1.0), r("MQ-TALADRO", 0.15), r(O1_ELE, 0.4), r(AYU, 0.2)],
         {"tipo": "Sensor de luz elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El sensor se toma del catálogo de productos."}),
        ("Iluminación exterior LED con fotocélula.", "ud",
         "Instalación de iluminación exterior LED con fotocélula, para ahorro. La luminaria la elige el cliente.",
         [r("MT-DOM-SENSOR-LUZ", 1.0), r("MT-ELE-CABLE", 2.0), r("MQ-TALADRO", 0.2), r(O1_ELE, 0.6), r(AYU, 0.3)],
         {"tipo": "Luminaria exterior LED elegida por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. La luminaria se toma del catálogo de productos."}),
        ("Sustitución de lámparas halógenas por LED.", "ud",
         "Sustitución de lámpara halógena por LED, con ajuste del portalámparas. La lámpara la elige el cliente.",
         [r("MT-ELE-CABLE", 0.5), r(O1_ELE, 0.3), r(AYU, 0.15)],
         {"tipo": "Lámpara LED elegida por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. La lámpara se toma del catálogo de productos."}),
        ("Sistema de control de iluminación por zonas.", "ud",
         "Instalación de sistema de control de iluminación por zonas, con pulsadores de escena. El sistema lo elige el cliente.",
         [r("MT-DOM-TECLADO", 1.0), r("MT-ELE-CABLE", 2.0), r("MQ-TALADRO", 0.2), r(O1_ELE, 0.7), r(AYU, 0.35)],
         {"tipo": "Sistema de control de iluminación elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El sistema se toma del catálogo de productos."}),
        ("Iluminación de bajo consumo en áreas comunes.", "ud",
         "Instalación de luminaria de bajo consumo en áreas comunes. La luminaria la elige el cliente.",
         [r("MT-ELE-CABLE", 2.0), r("MT-ELE-CAJA", 1.0), r("MQ-TALADRO", 0.2), r(O1_ELE, 0.6), r(AYU, 0.3)],
         {"tipo": "Luminaria de bajo consumo elegida por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. La luminaria se toma del catálogo de productos."}),
        ("Verificación de eficiencia de iluminación.", "glb",
         "Verificación de la eficiencia del sistema de iluminación, con medición de consumos.",
         [r("MQ-DETECTOR", 0.1), r(O1_ELE, 0.4), r(AYU, 0.2)]),
        ("Temporizador de iluminación de zonas comunes.", "ud",
         "Instalación de temporizador de iluminación de zonas comunes, para apagado automático. El temporizador lo elige el cliente.",
         [r("MT-DOM-ENCHUFE", 1.0), r("MT-ELE-CABLE", 1.0), r("MQ-TALADRO", 0.15), r(O1_ELE, 0.4), r(AYU, 0.2)],
         {"tipo": "Temporizador elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El temporizador se toma del catálogo de productos."}),
    ],
    "09": [
        ("Instalación de panel solar fotovoltaico.", "ud",
         "Instalación de panel solar fotovoltaico, con estructura y conexión. El panel lo elige el cliente.",
         [r("MT-PANEL-SOLAR", 1.0), r("MT-TORN-TECHO", 6.0), r("MQ-TALADRO", 0.3), r(O1_ELE, 1.5), r(AYU, 0.75)],
         {"tipo": "Panel solar elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El panel se toma del catálogo de productos."}),
        ("Instalación de inversor fotovoltaico.", "ud",
         "Instalación de inversor para sistema fotovoltaico, con conexión eléctrica. El inversor lo elige el cliente.",
         [r("MT-INVERSOR", 1.0), r("MT-ELE-CABLE", 3.0), r("MQ-TALADRO", 0.2), r(O1_ELE, 1.0), r(AYU, 0.5)],
         {"tipo": "Inversor elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El inversor se toma del catálogo de productos."}),
        ("Instalación de banco de baterías para fotovoltaica.", "ud",
         "Instalación de banco de baterías para sistema fotovoltaico, con conexión. Las baterías las elige el cliente.",
         [r("MT-BATERIA", 1.0), r("MT-ELE-CABLE", 3.0), r("MQ-TALADRO", 0.2), r(O1_ELE, 1.0), r(AYU, 0.5)],
         {"tipo": "Banco de baterías elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. Las baterías se toman del catálogo de productos."}),
        ("Sistema de agua caliente solar.", "ud",
         "Instalación de sistema de agua caliente solar, con conexión hidráulica. El sistema lo elige el cliente.",
         [r("MT-PLO-PPR20", 2.0), r("MT-PLO-SOP", 2.0), r("MQ-TALADRO", 0.25), r(O1_PLO, 1.2), r(AYU, 0.6)],
         {"tipo": "Sistema de agua caliente solar elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El sistema se toma del catálogo de productos."}),
        ("Estructura soporte de paneles solares.", "m²",
         "Ejecución de estructura soporte de paneles solares, con perfiles y fijación.",
         [r("MT-PERFIL-ACERO", 2.0), r("MT-PINT-ANTICORR", 0.05), r("MT-TORNILLO-EST", 4.0), r("MQ-TALADRO", 0.15), r(O1_SOLD, 0.5), r(AYU, 0.4)]),
        ("Conexión de sistema fotovoltaico a red.", "glb",
         "Conexión del sistema fotovoltaico a la red, con protecciones y puesta en marcha.",
         [r("MT-ELE-CABLE", 4.0), r("MT-BREAKER", 1.0), r("MQ-TALADRO", 0.2), r(O1_ELE, 1.0), r(AYU, 0.5)]),
        ("Medidor bidireccional de energía.", "ud",
         "Instalación de medidor bidireccional de energía, para la compensación de excedentes. El medidor lo elige el cliente.",
         [r("MT-ELE-CABLE", 2.0), r("MT-ELE-CAJA", 1.0), r("MQ-TALADRO", 0.2), r(O1_ELE, 0.6), r(AYU, 0.3)],
         {"tipo": "Medidor bidireccional elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El medidor se toma del catálogo de productos."}),
        ("Aerotermia para agua caliente.", "ud",
         "Instalación de sistema de aerotermia para agua caliente. El equipo lo elige el cliente.",
         [r("MT-TUB-FRIGO", 2.0), r("MT-PLO-PPR20", 2.0), r("MQ-TALADRO", 0.25), r(O1_AC, 1.5), r(AYU, 0.75)],
         {"tipo": "Sistema de aerotermia elegido por el cliente", "unidad": "ud", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El equipo se toma del catálogo de productos."}),
        ("Generación de respaldo con baterías.", "glb",
         "Instalación de sistema de respaldo con baterías, para autoconsumo. El sistema lo elige el cliente.",
         [r("MT-BATERIA", 1.0), r("MT-INVERSOR", 1.0), r("MT-ELE-CABLE", 3.0), r("MQ-TALADRO", 0.25), r(O1_ELE, 1.2), r(AYU, 0.6)],
         {"tipo": "Sistema de respaldo elegido por el cliente", "unidad": "glb", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El sistema se toma del catálogo de productos."}),
        ("Monitorización de producción fotovoltaica.", "glb",
         "Instalación de sistema de monitorización de la producción fotovoltaica. El sistema lo elige el cliente.",
         [r("MT-ELE-CABLE", 2.0), r("MT-ELE-CAJA", 1.0), r("MQ-TALADRO", 0.2), r(O1_ELE, 0.8), r(AYU, 0.4)],
         {"tipo": "Sistema de monitorización elegido por el cliente", "unidad": "glb", "consumo": 1.0, "nota": "La partida cubre solo la instalación. El sistema se toma del catálogo de productos."}),
        ("Mantenimiento de sistema fotovoltaico.", "glb",
         "Mantenimiento del sistema fotovoltaico, con limpieza de paneles y revisión de conexiones.",
         [r("MT-CONS-LIMP", 0.2), r(O1_ELE, 0.8), r(AYU, 0.4)]),
        ("Estructura de paneles solares sobre techo inclinado.", "m²",
         "Ejecución de estructura de soporte de paneles solares sobre techo inclinado, con fijación a la cubierta y sellado de los pasos.",
         [r("MT-PERFIL-ACERO", 2.0), r("MT-TORN-TECHO", 4.0), r("MT-SILICONA-EST", 0.02), r("MQ-TALADRO", 0.15), r(O1_SOLD, 0.5), r(AYU, 0.4)]),
    ],
}


def main() -> int:
    recursos = json.loads(RECURSOS.read_text(encoding="utf-8"))
    refs_validos = set()
    for grupo in ("materiales", "maquinaria", "mano_obra"):
        refs_validos.update(recursos[grupo].keys())

    # 1) apartados faltantes en clasificacion
    clasif = json.loads(CLASIF.read_text(encoding="utf-8"))
    apartados_nuevos = {
        "15": {"05": "Residuos especiales o peligrosos"},
        "16": {"01": "Ensayos de concreto, acero y mampostería",
               "02": "Inspección de soldaduras, anclajes y estructura",
               "03": "Pruebas de impermeabilización y estanqueidad",
               "04": "Pruebas de instalaciones sanitarias",
               "05": "Pruebas eléctricas y de puesta a tierra",
               "06": "Pruebas de climatización, ventilación y balanceo",
               "07": "Termografía, humedad y diagnóstico no destructivo",
               "08": "Puesta en marcha, protocolos y documentación final"},
        "17": {"05": "Seguridad en excavaciones y espacios confinados",
               "06": "Protección contra incendios durante la obra"},
        "18": {"01": "Diagnóstico y evaluación energética",
               "02": "Mejora térmica de fachadas",
               "03": "Mejora térmica de techos y cubiertas",
               "04": "Mejora térmica de pisos y entrepisos",
               "05": "Sustitución y mejora de ventanas y vidrios",
               "06": "Protección solar y control de ganancias térmicas",
               "07": "Mejora de climatización y ventilación",
               "08": "Iluminación eficiente y control",
               "09": "Incorporación de energías renovables"},
    }
    for cap, subs in apartados_nuevos.items():
        for sub, nombre in subs.items():
            nodo = clasif["capitulos"][cap]["subcapitulos"][sub]
            if "01" not in nodo["apartados"]:
                nodo["apartados"]["01"] = nombre

    # 2) generar partidas
    titulos = set()
    # cargar títulos existentes
    for ruta in DESCOMP.glob("*.json"):
        try:
            titulos.add(json.loads(ruta.read_text(encoding="utf-8"))["titulo"])
        except (OSError, ValueError, KeyError):
            pass

    nuevos = 0
    for cap, subcaps in (("15", CAP15), ("16", CAP16), ("17", CAP17), ("18", CAP18)):
        for sub, partidas in subcaps.items():
            n = 1
            for item in partidas:
                titulo, unidad, descripcion, recursos = item[0], item[1], item[2], item[3]
                producto_cliente = item[4] if len(item) > 4 else None
                codigo = f"{cap}.{sub}.01.{n*10:03d}"
                ruta = DESCOMP / f"{codigo}.json"
                while ruta.exists():
                    n += 1
                    codigo = f"{cap}.{sub}.01.{n*10:03d}"
                    ruta = DESCOMP / f"{codigo}.json"
                if titulo in titulos:
                    raise SystemExit(f"Título duplicado: {titulo}")
                titulos.add(titulo)
                for rec in recursos:
                    if rec["ref"] not in refs_validos:
                        raise SystemExit(f"Recurso desconocido en {codigo}: {rec['ref']}")
                partida = {
                    "codigo": codigo,
                    "ambito": "reforma",
                    "capitulo": cap,
                    "subcapitulo": sub,
                    "unidad": unidad,
                    "titulo": titulo,
                    "descripcion": descripcion,
                    "margen": 0.35,
                    "complementarios_pct": 1,
                    "recursos": recursos,
                    "codigo_covenin": "",
                    "codigo_legacy": "",
                    "apartado": "01",
                }
                if producto_cliente:
                    partida["producto_cliente"] = producto_cliente
                ruta.write_text(json.dumps(partida, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
                n += 1
                nuevos += 1

    CLASIF.write_text(json.dumps(clasif, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Generadas {nuevos} partidas nuevas (15, 16, 17 y 18).")
    print(f"Apartados añadidos: {sum(len(v) for v in apartados_nuevos.values())}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
