-- Cotizat / Supabase SQL Editor
-- Migracion Alembic f2a3b4c5d6e7; revision previa obligatoria: e1f2a3b4c5d6
-- Ejecutar en orden. No ejecutar si alembic_version no coincide.
BEGIN;
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM public.alembic_version WHERE version_num = 'e1f2a3b4c5d6') THEN
  RAISE EXCEPTION 'Revision previa incorrecta: se esperaba e1f2a3b4c5d6';
 END IF;
END $$;
CREATE TABLE IF NOT EXISTS public.precios_recursos_mercado (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 recurso_id integer NOT NULL REFERENCES public.recursos(id) ON DELETE CASCADE,
 pais_codigo varchar(2) NOT NULL,
 organizacion_id integer NULL REFERENCES public.organizaciones(id) ON DELETE CASCADE,
 precio double precision NOT NULL DEFAULT 0,
 moneda varchar(10) NOT NULL DEFAULT 'USD',
 fuente varchar(200) DEFAULT '', proveedor varchar(150) DEFAULT '', confianza varchar(20) DEFAULT 'referencia',
 fecha_vigencia date NULL, fecha_actualizacion timestamp NULL, activo boolean NOT NULL DEFAULT true,
 CONSTRAINT uq_precio_recurso_mercado_org UNIQUE (recurso_id,pais_codigo,organizacion_id)
);
CREATE INDEX IF NOT EXISTS ix_precios_recursos_mercado_recurso_id ON public.precios_recursos_mercado(recurso_id);
CREATE INDEX IF NOT EXISTS ix_precios_recursos_mercado_pais_codigo ON public.precios_recursos_mercado(pais_codigo);
CREATE INDEX IF NOT EXISTS ix_precios_recursos_mercado_organizacion_id ON public.precios_recursos_mercado(organizacion_id);
UPDATE public.alembic_version SET version_num = 'f2a3b4c5d6e7' WHERE version_num = 'e1f2a3b4c5d6';
COMMIT;
