-- CotizaT — actualización de b7c4a9e2d31f a c2f6e8a1d934
-- E3-017/E3-018/E3-019: enlaces revocables, respuesta, estado y avisos.
-- Ejecutar únicamente en Supabase SQL Editor con sesión administrativa.
-- No usar DATABASE_URL del runtime para aplicar DDL.

BEGIN;

DO $check$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.alembic_version
    WHERE version_num = 'b7c4a9e2d31f'
  ) THEN
    RAISE EXCEPTION
      'Se esperaba alembic_version b7c4a9e2d31f antes de c2f6e8a1d934';
  END IF;
END
$check$;

CREATE TABLE public.enlaces_propuesta (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id integer NOT NULL
    REFERENCES public.organizaciones(id) ON DELETE RESTRICT,
  presupuesto_id integer NOT NULL
    REFERENCES public.presupuestos(id) ON DELETE CASCADE,
  presupuesto_version_id integer NOT NULL
    REFERENCES public.presupuesto_versiones(id) ON DELETE CASCADE,
  presupuesto_version_numero integer NOT NULL,
  token_hash varchar(64) NOT NULL,
  token_prefix varchar(12) NOT NULL DEFAULT '',
  pdf_snapshot varchar(900) NOT NULL,
  empresa_nombre varchar(200) NOT NULL DEFAULT '',
  cliente_nombre varchar(200) NOT NULL DEFAULT '',
  presupuesto_numero varchar(20) NOT NULL DEFAULT '',
  presupuesto_titulo varchar(250) NOT NULL DEFAULT '',
  total double precision NOT NULL DEFAULT 0,
  moneda varchar(10) NOT NULL DEFAULT 'USD',
  fecha_presupuesto date NOT NULL,
  valido_hasta date NOT NULL,
  creado_por_usuario_id integer
    REFERENCES public.usuarios(id) ON DELETE SET NULL,
  expires_at timestamp without time zone NOT NULL,
  revoked_at timestamp without time zone,
  respuesta varchar(20) NOT NULL DEFAULT 'pendiente',
  respondido_por_nombre varchar(200) NOT NULL DEFAULT '',
  respondido_por_email varchar(254) NOT NULL DEFAULT '',
  respuesta_comentario text NOT NULL DEFAULT '',
  responded_at timestamp without time zone,
  estado_presupuesto_actualizado boolean NOT NULL DEFAULT false,
  notificacion_enviada_at timestamp without time zone,
  notificacion_destinatarios text NOT NULL DEFAULT '',
  notificacion_error text NOT NULL DEFAULT '',
  created_at timestamp without time zone NOT NULL,
  CONSTRAINT ck_enlace_propuesta_token_hash_sha256
    CHECK (length(token_hash) = 64),
  CONSTRAINT ck_enlace_propuesta_respuesta_valida
    CHECK (respuesta IN ('pendiente', 'aceptada', 'rechazada')),
  CONSTRAINT uq_enlace_propuesta_token_hash UNIQUE (token_hash)
);

CREATE INDEX ix_enlaces_propuesta_organizacion_id
  ON public.enlaces_propuesta (organizacion_id);
CREATE INDEX ix_enlaces_propuesta_presupuesto_creado
  ON public.enlaces_propuesta (presupuesto_id, created_at);

REVOKE ALL ON TABLE public.enlaces_propuesta FROM PUBLIC;
ALTER TABLE public.enlaces_propuesta ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enlaces_propuesta FORCE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON TABLE public.enlaces_propuesta TO cotizat_app;
GRANT USAGE, SELECT ON SEQUENCE public.enlaces_propuesta_id_seq TO cotizat_app;

CREATE POLICY cotizat_proposal_select_tenant
ON public.enlaces_propuesta FOR SELECT TO cotizat_app
USING (cotizat_security.tenant_access(organizacion_id, FALSE));

-- Única apertura pública: una fila, por SHA-256 exacto, vigente y no revocada.
-- No se abre ninguna política sobre clientes, presupuestos, versiones ni
-- archivos. La app lee el PDF por la referencia privada copiada en esta fila.
CREATE POLICY cotizat_proposal_select_public
ON public.enlaces_propuesta FOR SELECT TO cotizat_app
USING (
  token_hash = NULLIF(
    pg_catalog.current_setting('cotizat.proposal_token_hash', true),
    ''
  )
  AND revoked_at IS NULL
  AND expires_at > pg_catalog.clock_timestamp()
);

CREATE POLICY cotizat_proposal_insert_tenant
ON public.enlaces_propuesta FOR INSERT TO cotizat_app
WITH CHECK (cotizat_security.tenant_access(organizacion_id, TRUE));

CREATE POLICY cotizat_proposal_update_tenant
ON public.enlaces_propuesta FOR UPDATE TO cotizat_app
USING (cotizat_security.tenant_access(organizacion_id, TRUE))
WITH CHECK (cotizat_security.tenant_access(organizacion_id, TRUE));

-- La sesión pública no obtiene UPDATE sobre la tabla. Esta función solo puede
-- escribir la respuesta en la fila exacta del claim, una vez y mientras siga
-- vigente. El resto de columnas y tablas permanecen inaccesibles.
CREATE OR REPLACE FUNCTION cotizat_security.record_proposal_response(
  p_decision text,
  p_name text,
  p_email text,
  p_comment text
) RETURNS integer LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_id integer;
  v_budget_id integer;
  v_version_id integer;
  v_organization_id integer;
  v_version_number integer;
  v_state_updated integer := 0;
BEGIN
  IF p_decision NOT IN ('aceptada', 'rechazada')
     OR char_length(btrim(COALESCE(p_name, ''))) NOT BETWEEN 2 AND 200
     OR char_length(COALESCE(p_email, '')) > 254
     OR lower(COALESCE(p_email, '')) !~
        '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$'
     OR char_length(COALESCE(p_comment, '')) > 2000 THEN
    RETURN NULL;
  END IF;

  UPDATE public.enlaces_propuesta
  SET respuesta = p_decision,
      respondido_por_nombre = btrim(p_name),
      respondido_por_email = lower(btrim(p_email)),
      respuesta_comentario = btrim(COALESCE(p_comment, '')),
      responded_at = pg_catalog.clock_timestamp()
  WHERE token_hash = NULLIF(
          pg_catalog.current_setting('cotizat.proposal_token_hash', true), ''
        )
    AND respuesta = 'pendiente'
    AND revoked_at IS NULL
    AND expires_at > pg_catalog.clock_timestamp()
  RETURNING id, presupuesto_id, presupuesto_version_id, organizacion_id
  INTO v_id, v_budget_id, v_version_id, v_organization_id;

  IF v_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT numero_version INTO v_version_number
  FROM public.presupuesto_versiones
  WHERE id = v_version_id;

  UPDATE public.presupuestos
  SET estado = CASE p_decision
                 WHEN 'aceptada' THEN 'aprobado'
                 ELSE 'rechazado'
               END,
      updated_at = pg_catalog.clock_timestamp()
  WHERE id = v_budget_id
    AND estado IN ('enviado', 'reenviado')
    AND v_version_id = (
      SELECT pv.id FROM public.presupuesto_versiones AS pv
      WHERE pv.presupuesto_id = v_budget_id
      ORDER BY pv.numero_version DESC LIMIT 1
    );
  GET DIAGNOSTICS v_state_updated = ROW_COUNT;

  UPDATE public.enlaces_propuesta
  SET estado_presupuesto_actualizado = (v_state_updated = 1)
  WHERE id = v_id;

  INSERT INTO public.notas_seguimiento (
    presupuesto_id, texto, created_at, organizacion_id
  ) VALUES (
    v_budget_id,
    'Propuesta V' || COALESCE(v_version_number::text, '?') || ' ' ||
      p_decision || ' por ' || btrim(p_name) || ' (' || lower(btrim(p_email)) || ').',
    pg_catalog.clock_timestamp(),
    v_organization_id
  );

  RETURN v_id;
END
$$;

-- Destinatarios internos y constancia del resultado del correo. Ambas
-- funciones vuelven a exigir el hash del enlace; no exponen el tenant.
CREATE OR REPLACE FUNCTION cotizat_security.proposal_notification_recipients(
  p_link_id integer
) RETURNS TABLE(email varchar) LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT DISTINCT u.email
  FROM public.enlaces_propuesta AS l
  JOIN public.membresias AS m ON m.organizacion_id = l.organizacion_id
  JOIN public.usuarios AS u ON u.id = m.usuario_id
  WHERE l.id = p_link_id
    AND l.token_hash = NULLIF(
      pg_catalog.current_setting('cotizat.proposal_token_hash', true), ''
    )
    AND l.respuesta IN ('aceptada', 'rechazada')
    AND m.activa IS TRUE
    AND m.rol IN ('propietario', 'administrador')
    AND u.activo IS TRUE
$$;

CREATE OR REPLACE FUNCTION cotizat_security.mark_proposal_notification(
  p_link_id integer,
  p_recipients text,
  p_error text
) RETURNS integer LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_id integer;
BEGIN
  UPDATE public.enlaces_propuesta
  SET notificacion_destinatarios = left(COALESCE(p_recipients, ''), 2000),
      notificacion_error = left(COALESCE(p_error, ''), 1000),
      notificacion_enviada_at = CASE
        WHEN COALESCE(p_recipients, '') <> '' AND COALESCE(p_error, '') = ''
        THEN pg_catalog.clock_timestamp()
        ELSE NULL
      END
  WHERE id = p_link_id
    AND token_hash = NULLIF(
      pg_catalog.current_setting('cotizat.proposal_token_hash', true), ''
    )
    AND respuesta IN ('aceptada', 'rechazada')
  RETURNING id INTO v_id;
  RETURN v_id;
END
$$;

ALTER FUNCTION cotizat_security.record_proposal_response(text, text, text, text) OWNER TO CURRENT_USER;
ALTER FUNCTION cotizat_security.proposal_notification_recipients(integer) OWNER TO CURRENT_USER;
ALTER FUNCTION cotizat_security.mark_proposal_notification(integer, text, text) OWNER TO CURRENT_USER;

REVOKE ALL ON FUNCTION cotizat_security.record_proposal_response(text, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION cotizat_security.proposal_notification_recipients(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION cotizat_security.mark_proposal_notification(integer, text, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION cotizat_security.record_proposal_response(text, text, text, text) TO cotizat_app;
GRANT EXECUTE ON FUNCTION cotizat_security.proposal_notification_recipients(integer) TO cotizat_app;
GRANT EXECUTE ON FUNCTION cotizat_security.mark_proposal_notification(integer, text, text) TO cotizat_app;

UPDATE public.alembic_version
SET version_num = 'c2f6e8a1d934'
WHERE version_num = 'b7c4a9e2d31f';

COMMIT;

-- Verificación: una sola fila con el nuevo head.
SELECT version_num FROM public.alembic_version;

-- RLS debe estar activo y forzado.
SELECT relrowsecurity, relforcerowsecurity
FROM pg_catalog.pg_class
WHERE oid = 'public.enlaces_propuesta'::regclass;

-- Deben existir cuatro políticas; la pública solo SELECT.
SELECT polname, polcmd, pg_get_expr(polqual, polrelid) AS using_expr,
       pg_get_expr(polwithcheck, polrelid) AS check_expr
FROM pg_catalog.pg_policy
WHERE polrelid = 'public.enlaces_propuesta'::regclass
ORDER BY polname;
