-- CotizaT — actualización de d6e2f9c4b8a1 a e5f2a8d31b6c
-- Compras de plan con comprobante (E1-059 cobro manual).
-- Ejecutar una sola vez con el rol administrativo de Supabase/PostgreSQL.

BEGIN;

DO $$
DECLARE
  v_version text;
BEGIN
  SELECT version_num INTO v_version FROM public.alembic_version LIMIT 1;
  IF v_version IS DISTINCT FROM 'd6e2f9c4b8a1' THEN
    RAISE EXCEPTION
      'Se esperaba alembic_version d6e2f9c4b8a1 antes de e5f2a8d31b6c; se encontró %',
      COALESCE(v_version, '<vacío>');
  END IF;
END
$$;

CREATE TABLE public.compras_plan (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id integer NOT NULL REFERENCES public.organizaciones(id)
    ON DELETE RESTRICT,
  plan varchar(20) NOT NULL,
  metodo_pago varchar(30) NOT NULL,
  importe double precision NOT NULL DEFAULT 0,
  moneda varchar(10) NOT NULL DEFAULT 'USD',
  datos_verificacion text NOT NULL DEFAULT '{}',
  comprobante_reference varchar(500) NOT NULL DEFAULT '',
  comprobante_nombre varchar(255) NOT NULL DEFAULT '',
  comprobante_mime varchar(150) NOT NULL DEFAULT '',
  estado varchar(20) NOT NULL DEFAULT 'pendiente',
  creada_por_usuario_id integer REFERENCES public.usuarios(id)
    ON DELETE SET NULL,
  creada_por_email varchar(254) NOT NULL DEFAULT '',
  created_at timestamp,
  licencia_id integer REFERENCES public.licencias(id)
    ON DELETE SET NULL,
  revisado_por_email varchar(254) NOT NULL DEFAULT '',
  revisado_at timestamp,
  CONSTRAINT ck_compra_plan_valido CHECK (plan IN ('anual', 'mensual')),
  CONSTRAINT ck_compra_metodo_valido CHECK (
    metodo_pago IN ('pago_movil', 'binance', 'kontigo', 'usdt')
  ),
  CONSTRAINT ck_compra_estado_valido CHECK (
    estado IN ('pendiente', 'activa', 'rechazada')
  ),
  CONSTRAINT ck_compra_importe_no_negativo CHECK (importe >= 0)
);

CREATE INDEX ix_compras_plan_organizacion
  ON public.compras_plan(organizacion_id);
CREATE INDEX ix_compras_plan_estado
  ON public.compras_plan(organizacion_id, estado, created_at);

-- RLS: tenant para el cliente, operador para el panel del titular.
REVOKE ALL ON TABLE public.compras_plan FROM PUBLIC;
ALTER TABLE public.compras_plan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compras_plan FORCE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON TABLE public.compras_plan TO cotizat_app;
GRANT USAGE, SELECT ON SEQUENCE public.compras_plan_id_seq TO cotizat_app;

DROP POLICY IF EXISTS cotizat_compra_select_tenant ON public.compras_plan;
CREATE POLICY cotizat_compra_select_tenant ON public.compras_plan
  FOR SELECT TO cotizat_app
  USING (cotizat_security.tenant_access(organizacion_id, FALSE));

DROP POLICY IF EXISTS cotizat_compra_select_operator ON public.compras_plan;
CREATE POLICY cotizat_compra_select_operator ON public.compras_plan
  FOR SELECT TO cotizat_app
  USING (COALESCE(
    pg_catalog.current_setting('cotizat.es_operador', true) = 'on',
    FALSE
  ));

DROP POLICY IF EXISTS cotizat_compra_insert_tenant ON public.compras_plan;
CREATE POLICY cotizat_compra_insert_tenant ON public.compras_plan
  FOR INSERT TO cotizat_app
  WITH CHECK (cotizat_security.tenant_access(organizacion_id, TRUE));

DROP POLICY IF EXISTS cotizat_compra_update_operator ON public.compras_plan;
CREATE POLICY cotizat_compra_update_operator ON public.compras_plan
  FOR UPDATE TO cotizat_app
  USING (COALESCE(
    pg_catalog.current_setting('cotizat.es_operador', true) = 'on',
    FALSE
  ))
  WITH CHECK (COALESCE(
    pg_catalog.current_setting('cotizat.es_operador', true) = 'on',
    FALSE
  ));

UPDATE public.alembic_version
SET version_num = 'e5f2a8d31b6c'
WHERE version_num = 'd6e2f9c4b8a1';

COMMIT;

-- Verificación:
-- SELECT version_num FROM public.alembic_version;
-- SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename = 'compras_plan';
-- SELECT polname FROM pg_policies WHERE tablename = 'compras_plan' ORDER BY polname;
--   → cotizat_compra_insert_tenant, cotizat_compra_select_operator,
--     cotizat_compra_select_tenant, cotizat_compra_update_operator
