-- Cotizat / Supabase SQL Editor
-- Migracion a3b4c5d6e7f8; revision previa obligatoria: f2a3b4c5d6e7
BEGIN;
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM public.alembic_version WHERE version_num = 'f2a3b4c5d6e7') THEN
  RAISE EXCEPTION 'Revision previa incorrecta: se esperaba f2a3b4c5d6e7';
 END IF;
END $$;
ALTER TABLE public.descomposicion_filas ADD COLUMN IF NOT EXISTS moneda varchar(10) DEFAULT 'USD';
ALTER TABLE public.descomposicion_filas ADD COLUMN IF NOT EXISTS origen_precio varchar(20) DEFAULT 'base';
ALTER TABLE public.descomposicion_filas ADD COLUMN IF NOT EXISTS confianza_precio varchar(20) DEFAULT 'provisional';
ALTER TABLE public.descomposicion_filas ADD COLUMN IF NOT EXISTS fuente_precio varchar(200) DEFAULT '';
CREATE TABLE IF NOT EXISTS public.historial_precios_recursos (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 precio_mercado_id integer NOT NULL REFERENCES public.precios_recursos_mercado(id) ON DELETE CASCADE,
 precio_anterior double precision, precio_nuevo double precision NOT NULL,
 moneda varchar(10) NOT NULL DEFAULT 'USD', fecha timestamp NULL,
 motivo varchar(250) DEFAULT '', fuente varchar(200) DEFAULT ''
);
CREATE INDEX IF NOT EXISTS ix_historial_precios_recursos_precio_mercado_id ON public.historial_precios_recursos(precio_mercado_id);
UPDATE public.alembic_version SET version_num = 'a3b4c5d6e7f8' WHERE version_num = 'f2a3b4c5d6e7';
COMMIT;
