-- CotizaT — actualización de f6d1a9c3e8b2 a g7c8d9e0f1a2
-- Conversaciones del asistente, mensajes tenant y lectura restringida en Admin.
-- Ejecutar una sola vez en Supabase → SQL Editor con el rol administrativo.

BEGIN;

DO $$
DECLARE
  v_version text;
BEGIN
  SELECT version_num INTO v_version
  FROM public.alembic_version
  LIMIT 1;
  IF v_version IS DISTINCT FROM 'f6d1a9c3e8b2' THEN
    RAISE EXCEPTION
      'Se esperaba alembic_version f6d1a9c3e8b2 antes de g7c8d9e0f1a2; se encontró %',
      COALESCE(v_version, '<vacío>');
  END IF;
END
$$;

CREATE TABLE public.conversaciones_ia (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id integer NOT NULL REFERENCES public.organizaciones(id) ON DELETE RESTRICT,
  public_id varchar(64) NOT NULL,
  usuario_id integer NULL REFERENCES public.usuarios(id) ON DELETE SET NULL,
  usuario_email varchar(254) NOT NULL DEFAULT '',
  titulo varchar(180) NOT NULL DEFAULT '',
  pagina_inicio varchar(240) NOT NULL DEFAULT '',
  estado varchar(20) NOT NULL DEFAULT 'activa',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultimo_mensaje_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_conversacion_ia_public_id UNIQUE (public_id),
  CONSTRAINT ck_conversacion_ia_estado_valido
    CHECK (estado IN ('activa', 'archivada'))
);

CREATE INDEX ix_conversaciones_ia_org_ultimo
  ON public.conversaciones_ia (organizacion_id, ultimo_mensaje_at);
CREATE INDEX ix_conversaciones_ia_org_usuario
  ON public.conversaciones_ia (organizacion_id, usuario_id);
CREATE INDEX ix_conversaciones_ia_usuario_id
  ON public.conversaciones_ia (usuario_id);
CREATE INDEX ix_conversaciones_ia_expira
  ON public.conversaciones_ia (expires_at);

CREATE TABLE public.mensajes_ia (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id integer NOT NULL REFERENCES public.organizaciones(id) ON DELETE RESTRICT,
  conversacion_id integer NOT NULL REFERENCES public.conversaciones_ia(id) ON DELETE CASCADE,
  rol varchar(20) NOT NULL,
  contenido text NOT NULL,
  orden integer NOT NULL,
  turn_id varchar(80) NULL,
  completo boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_mensaje_ia_rol_valido CHECK (rol IN ('user', 'assistant')),
  CONSTRAINT ck_mensaje_ia_orden_no_negativo CHECK (orden >= 0),
  CONSTRAINT uq_mensaje_ia_conversacion_orden UNIQUE (conversacion_id, orden),
  CONSTRAINT uq_mensaje_ia_conversacion_turno_rol
    UNIQUE (conversacion_id, rol, turn_id)
);

CREATE INDEX ix_mensajes_ia_conversacion_orden
  ON public.mensajes_ia (conversacion_id, orden);
CREATE INDEX ix_mensajes_ia_conversacion_id
  ON public.mensajes_ia (conversacion_id);
CREATE INDEX ix_mensajes_ia_org_fecha
  ON public.mensajes_ia (organizacion_id, created_at);

-- Defensa en profundidad: la sesión normal solo ve/escribe su tenant; la
-- sesión marcada por get_operator_db puede leer y purgar todas las filas.
REVOKE ALL ON TABLE public.conversaciones_ia FROM PUBLIC;
REVOKE ALL ON TABLE public.mensajes_ia FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.conversaciones_ia TO cotizat_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.mensajes_ia TO cotizat_app;
GRANT USAGE, SELECT ON SEQUENCE public.conversaciones_ia_id_seq TO cotizat_app;
GRANT USAGE, SELECT ON SEQUENCE public.mensajes_ia_id_seq TO cotizat_app;

ALTER TABLE public.conversaciones_ia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversaciones_ia FORCE ROW LEVEL SECURITY;
ALTER TABLE public.mensajes_ia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mensajes_ia FORCE ROW LEVEL SECURITY;

CREATE POLICY cotizat_conversaciones_ia_select_tenant
  ON public.conversaciones_ia FOR SELECT TO cotizat_app
  USING (cotizat_security.tenant_access(organizacion_id, FALSE));
CREATE POLICY cotizat_conversaciones_ia_select_operator
  ON public.conversaciones_ia FOR SELECT TO cotizat_app
  USING (COALESCE(current_setting('cotizat.es_operador', true) = 'on', FALSE));
CREATE POLICY cotizat_conversaciones_ia_insert_tenant
  ON public.conversaciones_ia FOR INSERT TO cotizat_app
  WITH CHECK (cotizat_security.tenant_access(organizacion_id, TRUE));
CREATE POLICY cotizat_conversaciones_ia_update_tenant
  ON public.conversaciones_ia FOR UPDATE TO cotizat_app
  USING (cotizat_security.tenant_access(organizacion_id, TRUE))
  WITH CHECK (cotizat_security.tenant_access(organizacion_id, TRUE));
CREATE POLICY cotizat_conversaciones_ia_update_operator
  ON public.conversaciones_ia FOR UPDATE TO cotizat_app
  USING (COALESCE(current_setting('cotizat.es_operador', true) = 'on', FALSE))
  WITH CHECK (COALESCE(current_setting('cotizat.es_operador', true) = 'on', FALSE));
CREATE POLICY cotizat_conversaciones_ia_delete_tenant
  ON public.conversaciones_ia FOR DELETE TO cotizat_app
  USING (cotizat_security.tenant_access(organizacion_id, TRUE));
CREATE POLICY cotizat_conversaciones_ia_delete_operator
  ON public.conversaciones_ia FOR DELETE TO cotizat_app
  USING (COALESCE(current_setting('cotizat.es_operador', true) = 'on', FALSE));

CREATE POLICY cotizat_mensajes_ia_select_tenant
  ON public.mensajes_ia FOR SELECT TO cotizat_app
  USING (cotizat_security.tenant_access(organizacion_id, FALSE));
CREATE POLICY cotizat_mensajes_ia_select_operator
  ON public.mensajes_ia FOR SELECT TO cotizat_app
  USING (COALESCE(current_setting('cotizat.es_operador', true) = 'on', FALSE));
CREATE POLICY cotizat_mensajes_ia_insert_tenant
  ON public.mensajes_ia FOR INSERT TO cotizat_app
  WITH CHECK (
    cotizat_security.tenant_access(organizacion_id, TRUE)
    AND EXISTS (
      SELECT 1 FROM public.conversaciones_ia c
      WHERE c.id = conversacion_id
        AND c.organizacion_id = public.mensajes_ia.organizacion_id
    )
  );
CREATE POLICY cotizat_mensajes_ia_update_tenant
  ON public.mensajes_ia FOR UPDATE TO cotizat_app
  USING (
    cotizat_security.tenant_access(organizacion_id, TRUE)
    AND EXISTS (
      SELECT 1 FROM public.conversaciones_ia c
      WHERE c.id = conversacion_id
        AND c.organizacion_id = public.mensajes_ia.organizacion_id
    )
  )
  WITH CHECK (
    cotizat_security.tenant_access(organizacion_id, TRUE)
    AND EXISTS (
      SELECT 1 FROM public.conversaciones_ia c
      WHERE c.id = conversacion_id
        AND c.organizacion_id = public.mensajes_ia.organizacion_id
    )
  );
CREATE POLICY cotizat_mensajes_ia_update_operator
  ON public.mensajes_ia FOR UPDATE TO cotizat_app
  USING (COALESCE(current_setting('cotizat.es_operador', true) = 'on', FALSE))
  WITH CHECK (COALESCE(current_setting('cotizat.es_operador', true) = 'on', FALSE));
CREATE POLICY cotizat_mensajes_ia_delete_tenant
  ON public.mensajes_ia FOR DELETE TO cotizat_app
  USING (cotizat_security.tenant_access(organizacion_id, TRUE));
CREATE POLICY cotizat_mensajes_ia_delete_operator
  ON public.mensajes_ia FOR DELETE TO cotizat_app
  USING (COALESCE(current_setting('cotizat.es_operador', true) = 'on', FALSE));

-- Actualiza también el borrado verificado de una organización: mensajes e
-- hilos deben desaparecer antes de licencias/membresías/organización.
CREATE OR REPLACE FUNCTION cotizat_security.baja_organizacion(
  p_organization_id integer
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_role text;
BEGIN
  IF COALESCE(current_setting('cotizat.organization_id', true), '')
       <> p_organization_id::text THEN
    RAISE EXCEPTION
      'La baja no coincide con la organización de la sesión.'
      USING ERRCODE = '42501';
  END IF;

  v_role := cotizat_security.membership_role(p_organization_id);
  IF v_role IS DISTINCT FROM 'propietario' THEN
    RAISE EXCEPTION
      'Solo el propietario puede dar de baja la organización.'
      USING ERRCODE = '42501';
  END IF;

  DELETE FROM public.enlaces_propuesta WHERE organizacion_id = p_organization_id;
  DELETE FROM public.pagos WHERE organizacion_id = p_organization_id;
  DELETE FROM public.cambio_alcance_items WHERE organizacion_id = p_organization_id;
  DELETE FROM public.cambios_alcance WHERE organizacion_id = p_organization_id;
  DELETE FROM public.proyectos WHERE organizacion_id = p_organization_id;
  DELETE FROM public.notas_seguimiento WHERE organizacion_id = p_organization_id;
  DELETE FROM public.presupuesto_anexos WHERE organizacion_id = p_organization_id;
  DELETE FROM public.borradores_presupuesto WHERE organizacion_id = p_organization_id;
  DELETE FROM public.presupuesto_versiones WHERE organizacion_id = p_organization_id;
  DELETE FROM public.descomposicion_filas WHERE organizacion_id = p_organization_id;
  DELETE FROM public.descomposiciones_partida WHERE organizacion_id = p_organization_id;
  DELETE FROM public.mediciones WHERE organizacion_id = p_organization_id;
  DELETE FROM public.presupuesto_item_productos WHERE organizacion_id = p_organization_id;
  DELETE FROM public.presupuesto_items WHERE organizacion_id = p_organization_id;
  DELETE FROM public.capitulos WHERE organizacion_id = p_organization_id;
  DELETE FROM public.presupuestos WHERE organizacion_id = p_organization_id;
  DELETE FROM public.factura_items WHERE organizacion_id = p_organization_id;
  DELETE FROM public.factura_capitulos WHERE organizacion_id = p_organization_id;
  DELETE FROM public.facturas WHERE organizacion_id = p_organization_id;
  DELETE FROM public.clientes WHERE organizacion_id = p_organization_id;
  DELETE FROM public.partidas WHERE organizacion_id = p_organization_id;
  DELETE FROM public.productos WHERE organizacion_id = p_organization_id;
  DELETE FROM public.recursos WHERE organizacion_id = p_organization_id;
  DELETE FROM public.plantillas WHERE organizacion_id = p_organization_id;
  DELETE FROM public.recetas_estancia WHERE organizacion_id = p_organization_id;
  DELETE FROM public.categorias_partidas WHERE organizacion_id = p_organization_id;
  DELETE FROM public.archivos_almacenados WHERE organizacion_id = p_organization_id;
  DELETE FROM public.invitaciones_organizacion WHERE organizacion_id = p_organization_id;
  DELETE FROM public.configuracion WHERE organizacion_id = p_organization_id;
  DELETE FROM public.compras_plan WHERE organizacion_id = p_organization_id;
  DELETE FROM public.eventos_auditoria WHERE organizacion_id = p_organization_id;
  DELETE FROM public.mensajes_ia WHERE organizacion_id = p_organization_id;
  DELETE FROM public.conversaciones_ia WHERE organizacion_id = p_organization_id;
  DELETE FROM public.licencias WHERE organizacion_id = p_organization_id;
  DELETE FROM public.membresias WHERE organizacion_id = p_organization_id;
  DELETE FROM public.organizaciones WHERE id = p_organization_id;
END
$$;

ALTER FUNCTION cotizat_security.baja_organizacion(integer) OWNER TO CURRENT_USER;
REVOKE ALL ON FUNCTION cotizat_security.baja_organizacion(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION cotizat_security.baja_organizacion(integer) TO cotizat_app;

UPDATE public.alembic_version
SET version_num = 'g7c8d9e0f1a2'
WHERE version_num = 'f6d1a9c3e8b2';

COMMIT;

-- Verificación:
-- SELECT version_num FROM public.alembic_version;  → g7c8d9e0f1a2
-- SELECT relrowsecurity, relforcerowsecurity
-- FROM pg_class WHERE oid IN ('public.conversaciones_ia'::regclass,
--                             'public.mensajes_ia'::regclass);
