-- Cotizat / Supabase SQL Editor
-- Ruta consolidada para bases cuyo version_num actual es d9e2f3a4b5c6.
-- Incluye los cambios monetarios/mercado posteriores sin repetir d9.
BEGIN;
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM public.alembic_version WHERE version_num = 'd9e2f3a4b5c6') THEN
  RAISE EXCEPTION 'Revision previa incorrecta: se esperaba d9e2f3a4b5c6';
 END IF;
END $$;
ALTER TABLE public.configuracion ADD COLUMN IF NOT EXISTS moneda_base_catalogo varchar(10) DEFAULT 'USD';
ALTER TABLE public.presupuestos ADD COLUMN IF NOT EXISTS moneda_base varchar(10) DEFAULT 'USD';
ALTER TABLE public.presupuestos ADD COLUMN IF NOT EXISTS fuente_tipo_cambio varchar(120) DEFAULT '';
ALTER TABLE public.proyectos ADD COLUMN IF NOT EXISTS moneda_contractual varchar(10) DEFAULT 'USD';
ALTER TABLE public.proyectos ADD COLUMN IF NOT EXISTS moneda_base varchar(10) DEFAULT 'USD';
ALTER TABLE public.proyectos ADD COLUMN IF NOT EXISTS tipo_cambio double precision;
ALTER TABLE public.proyectos ADD COLUMN IF NOT EXISTS fecha_tipo_cambio date;
ALTER TABLE public.proyectos ADD COLUMN IF NOT EXISTS fuente_tipo_cambio varchar(120) DEFAULT '';
ALTER TABLE public.presupuesto_versiones ADD COLUMN IF NOT EXISTS moneda varchar(10) DEFAULT 'USD';
ALTER TABLE public.presupuesto_versiones ADD COLUMN IF NOT EXISTS moneda_base varchar(10) DEFAULT 'USD';
ALTER TABLE public.presupuesto_versiones ADD COLUMN IF NOT EXISTS tipo_cambio double precision;
ALTER TABLE public.presupuesto_versiones ADD COLUMN IF NOT EXISTS fecha_tipo_cambio date;
ALTER TABLE public.presupuesto_versiones ADD COLUMN IF NOT EXISTS fuente_tipo_cambio varchar(120) DEFAULT '';
ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS moneda_base varchar(10) DEFAULT 'USD';
ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS tipo_cambio double precision;
ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS fecha_tipo_cambio date;
ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS fuente_tipo_cambio varchar(120) DEFAULT '';
ALTER TABLE public.presupuesto_items ADD COLUMN IF NOT EXISTS moneda varchar(10) DEFAULT 'USD';
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS moneda varchar(10) DEFAULT 'USD';
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS moneda varchar(10) DEFAULT 'USD';
ALTER TABLE public.cambios_alcance ADD COLUMN IF NOT EXISTS moneda varchar(10) DEFAULT 'USD';
ALTER TABLE public.cambio_alcance_items ADD COLUMN IF NOT EXISTS moneda varchar(10) DEFAULT 'USD';
ALTER TABLE public.configuracion ADD COLUMN IF NOT EXISTS fuente_tipo_cambio varchar(120) DEFAULT '';
CREATE TABLE IF NOT EXISTS public.precios_recursos_mercado (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 recurso_id integer NOT NULL REFERENCES public.recursos(id) ON DELETE CASCADE,
 pais_codigo varchar(2) NOT NULL,
 organizacion_id integer NULL REFERENCES public.organizaciones(id) ON DELETE CASCADE,
 precio double precision NOT NULL DEFAULT 0,
 moneda varchar(10) NOT NULL DEFAULT 'USD', fuente varchar(200) DEFAULT '', proveedor varchar(150) DEFAULT '', confianza varchar(20) DEFAULT 'referencia', fecha_vigencia date NULL, fecha_actualizacion timestamp NULL, activo boolean NOT NULL DEFAULT true,
 CONSTRAINT uq_precio_recurso_mercado_org UNIQUE (recurso_id,pais_codigo,organizacion_id));
CREATE INDEX IF NOT EXISTS ix_precios_recursos_mercado_recurso_id ON public.precios_recursos_mercado(recurso_id);
CREATE INDEX IF NOT EXISTS ix_precios_recursos_mercado_pais_codigo ON public.precios_recursos_mercado(pais_codigo);
CREATE INDEX IF NOT EXISTS ix_precios_recursos_mercado_organizacion_id ON public.precios_recursos_mercado(organizacion_id);
ALTER TABLE public.descomposicion_filas ADD COLUMN IF NOT EXISTS moneda varchar(10) DEFAULT 'USD';
ALTER TABLE public.descomposicion_filas ADD COLUMN IF NOT EXISTS origen_precio varchar(20) DEFAULT 'base';
ALTER TABLE public.descomposicion_filas ADD COLUMN IF NOT EXISTS confianza_precio varchar(20) DEFAULT 'provisional';
ALTER TABLE public.descomposicion_filas ADD COLUMN IF NOT EXISTS fuente_precio varchar(200) DEFAULT '';
CREATE TABLE IF NOT EXISTS public.historial_precios_recursos (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, precio_mercado_id integer NOT NULL REFERENCES public.precios_recursos_mercado(id) ON DELETE CASCADE, precio_anterior double precision, precio_nuevo double precision NOT NULL, moneda varchar(10) NOT NULL DEFAULT 'USD', fecha timestamp NULL, motivo varchar(250) DEFAULT '', fuente varchar(200) DEFAULT '');
CREATE INDEX IF NOT EXISTS ix_historial_precios_recursos_precio_mercado_id ON public.historial_precios_recursos(precio_mercado_id);
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS subtipo varchar(40) DEFAULT '';
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS capacidad varchar(80) DEFAULT '';
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS modalidad_tarifa varchar(30) DEFAULT 'hora';
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS incluye_operador boolean DEFAULT false;
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS incluye_combustible boolean DEFAULT false;
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS incluye_flete boolean DEFAULT false;
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS rendimiento_jornada double precision;
ALTER TABLE public.recursos ADD COLUMN IF NOT EXISTS horas_jornada_recurso double precision DEFAULT 8.0;
UPDATE public.alembic_version SET version_num = 'c5d6e7f8a9b0' WHERE version_num = 'd9e2f3a4b5c6';
COMMIT;
